### ISSUE TITLE
Add information how to properly set up checked-out code with GO... env variables

### ISSUE THREAD

**Issue by januszm** [actions/setup-go#102]
Most basic setup with the following steps:

```yml
- uses: actions/checkout@v2
...
- uses: actions/setup-go@v2
```

will fail during `dep ensure` or `go test ./...` :
```
/home/runner/work/myproject/myproject is not within a known GOPATH/src
```

I must admit that with a little bit of searching I couldn't easily configure it.
Currently it starts with empty directories:

```
/home/runner/go
/home/runner/go/bin
```

The code after checkout is in:
```
/home/runner/work/REPOSITORY/REPOSITORY
```

It would be worth adding some instructions on how to modify the "checkout" step or how to set environment variables or what shell commands to execute to make it all work.

**Comment by longwuyuan** [comment]
https://github.community/t/go-import-path-in-travis-has-no-equivalent-in-github-actions/157968

**Comment by januszm** [comment]
I got it to work with this yml:

```yml
env:
  GOPATH: ${{ github.workspace }}
  GOBIN: ${{ github.workspace }}/bin
defaults:
  run:
    working-directory: ${{ env.GOPATH }}/src/myproject
steps:
  - uses: actions/checkout@v2
    with:
      fetch-depth: 1
      path: ${{ env.GOPATH }}/src/myproject
  - name: Set up Go
    uses: actions/setup-go@v2
    with:
      go-version: ...
```

The key was to set this: "working-directory: ${{ env.GOPATH }}/src/myproject" and be consistent.
An equivalent of Travis's `go_import_path` is to define `path: ${{ env.GOPATH }}/src/myproject` for checkout and `working-directory`
