### ISSUE TITLE
sudo issue

### ISSUE THREAD

**Issue by mehrdadrad** [actions/setup-go#104]
I configured go-version 1.15 and everything works properly without sudo. once I put the sudo then the Go available version with supper user is 1.14.x. any workaround to have Go 1.15 for supper user? 

```yaml
  runs-on: ubuntu-20.04
  steps:
     - name: Set up Golang
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15
     - name: Check out code
        uses: actions/checkout@v2
     - name: Test
        run: sudo go test ./... -timeout 5m
```
you can see what happened [here](https://github.com/mehrdadrad/tcpdog/runs/1876951079?check_suite_focus=true)
