### ISSUE TITLE
Support for arm 32-bit

### ISSUE THREAD

**Issue by jkowalski** [actions/setup-go#106]
Could 32-bit ARM support be added?

I tried this with my self-hosted runner on Raspberry PI:

```
    - name: Set up Go.
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16
      id: go
```

and got:

```
Setup go stable version spec ^1.16
Attempting to download ^1.16...
matching ^1.16...
Not found in manifest.  Falling back to download directly from Go
Error: Unable to find Go version '^1.16' for platform linux and architecture arm.
```

The binary to use in this case is: `https://golang.org/dl/go1.16.linux-armv6l.tar.gz`

**Comment by jnummelin** [comment]
Stumbling on this same pothole 😭 

Any known workarounds?

As I read the code it should pick up the `arm` -> `armv6l` naming mapping but evidently it just fails miserably.

How to enable debug loggin on the action when running it on a repo? I tried with:
```
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        env:
          ACTIONS_STEP_DEBUG: "true"
        with:
          go-version: 1.15
        id: go
```
but that does not output anything more.
