### ISSUE TITLE
compile: version "go1.16.2" does not match go tool version "go1.15.8"

### ISSUE THREAD

**Issue by fatedier** [actions/setup-go#107]
Failed case:
https://github.com/fatedier/release-test/runs/2121758524?check_suite_focus=true

```
- name: Set up Go
  uses: actions/setup-go@v2
  with:
    go-version: '1.16.2'
```

Workflow file:
https://github.com/fatedier/release-test/actions/runs/657671091/workflow

I'm not sure why there are go1.15.8 version.
