### ISSUE TITLE
"x509: certificate signed by unknown authority" when used in a container

### ISSUE THREAD

**Issue by kousu** [actions/setup-go#110]
When I `uses: actions/setup-go@v2` in combination with `container:` I get

> go get: module github.com/pacur/pacur: Get "https://proxy.golang.org/github.com/pacur/pacur/@v/list": x509: certificate signed by unknown authority

This is a known problem: https://medium.com/the-go-journey/x509-certificate-signed-by-unknown-authority-running-a-go-app-inside-a-docker-container-a12869337eb.

Is there anything `setup-go` can do to mitigate it? Maybe hardcode a big list of all the common ways to install `ca-certificates`? If it just did:

```
for pkg in apt apk pacman yum; do $pkg install ca-certificates; done
```

The problem would go away.

## Reproduction

With [this workflow](https://github.com/kousu/dehydrated-hooks/blob/30c5a114768a65760d7ef077be0d363f2fafb82b/.github/workflows/publish.yml):

```
name: Publish Linux Packages

on:
  # publish from the Releases page:
  release:
    types: [published]
  # publish from the Actions page:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version (e.g. 2.0.3)'
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        plat:
          - 'ubuntu:18.04'
          - 'ubuntu:20.04'
          - 'debian:sid'
          - 'archlinux'
    container: ${{matrix.plat}}
    
    steps:
      - run: echo "${{toJSON(github.event)}}"
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.13.1'
      - run: go get github.com/pacur/pacur
      # pacur has a silly idea of how to do I/O: it EXPECTS to be run
      # under docker and does all it's input and output in /pacur.
      - run: sudo mkdir -p /pacur && sudo cp dist/PKGBUILD /pacur
      #- run: sudo sed -i 's/pkgver=.*/pkgver=${{}}/' # TODO: edit the PKGBUILD to point at the new version
      # %:* is bash for 'remove any suffix starting from :', i.e. drop the container's
      # pacur's list of platforms doesn't line up exactly with the list on docker.io
      # but this should make it match for all the platforms we're using, at least
      - run: pacur build \$(${{ matrix.plat }}%:*}
      - run: sudo rm /pacur/PKGBUILD # avoid uploading this
      - uses: softprops/action-gh-release@v1
        with:
          files: '/pacur/*'
          fail_on_unmatched_files: true
          tag_name: ${{ github.event.inputs.version }} # in the workflow_dispatch case, make a new tag from the given input; in the published release case, this will be empty and will fall back to updating that release.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

I [get this](https://github.com/kousu/dehydrated-hooks/runs/2316278550).
