### ISSUE TITLE
Feature request: Support built-in cache

### ISSUE THREAD

**Issue by qsliu2017** [actions/setup-go#130]
I always use [actions/cache](https://github.com/marketplace/actions/cache) to cache the default location for cache data, and I think this should be a built-in feature of this action, like [setup-node supports dependency caching](https://github.blog/changelog/2021-07-02-github-actions-setup-node-now-supports-dependency-caching).

**Comment by sebastianst** [comment]
That'd be awesome. For reference, [`actions/cache` recommends the following step in your job for Go repos (Linux)](https://github.com/actions/cache/blob/main/examples.md#go---modules):
```yaml
- uses: actions/cache@v2
  with:
    path: |
      ~/.cache/go-build
      ~/go/pkg/mod
    key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
    restore-keys: |
      ${{ runner.os }}-go-
```

A nice start would be to mention this `actions/cache` setup in the README.
