### ISSUE TITLE
Impossible set up 1.17-rc1

### ISSUE THREAD

**Issue by dpogorzelski** [actions/setup-go#135]
Hey, it seems like there is no way to use 1.17-rc1, i tried a few combinations but they all result in 👍 
`Unable to find Go version '1.17-rc1' for platform linux and architecture x64`

some examples i tested:
```yaml
- name: Set up Go
  uses: actions/setup-go@v2
  with:
    go-version: 1.17-rc1
```

```yaml
- name: Set up Go
  uses: actions/setup-go@v2
  with:
    go-version: 1.17rc1
```

```yaml
- name: Set up Go
  uses: actions/setup-go@v2
  with:
    go-version: go1.17rc1
```

```yaml
- name: Set up Go
  uses: actions/setup-go@v2
  with:
    go-version: go1.17-rc1
```

I tried setting stable: 'false' for all of them as well but no luck.

**Comment by mfridman** [comment]
@dpogorzelski Did you end up getting an answer and/or something working?

**Comment by kevincobain2000** [comment]
Hi @mfridman, not sure why the manifest is not updated. The golang registry almost always has the tar available. You can check this out https://github.com/kevincobain2000/gobrew#setup-go-in-github-actions which uses the registry path below to get the latest tar.

https://github.com/kevincobain2000/gobrew/blob/01dcb1ebd16c12feac27d8339aa82c511d7ac56b/gobrew.go#L21

So far as I can see, that go1.17rc1 is updated on the manifest https://golang.org/dl/?mode=json&include=all which is used here https://github.com/actions/setup-go/blob/3b4dc6cbed1779f759b9c638cb83696acea809d1/src/installer.ts#L193

It should be ok tho.

**Comment by maxim-lobanov** [comment]
You should specify `stable: false` argument to install unstable versions.
See example:
```
- name: Set up Go
  uses: actions/setup-go@v2
  with:
    go-version: 1.17.0-rc1
    stable: false
```
