### ISSUE TITLE
Add $GOPATH/bin to $PATH

### ISSUE THREAD

**Issue by lmittmann** [actions/setup-go#14]
When installing tools via `go get` (e.g. golint) they can not be ran without adding `$GOPATH/bin` to `$PATH` beforehand.

So for using e.g. golint one would need to write a step:
```yml
- run: |
    export PATH=$PATH:$(go env GOPATH)/bin
    go get -u golang.org/x/lint/golint
    golint -set_exit_status ./...
```

It would be cool, if setup-go could already do the `export PATH=$PATH:$(go env GOPATH)/bin` part, as this is a common need.

**Comment by geoah** [comment]
GOBIN would be a better choice I think for this

**Comment by lmittmann** [comment]
`$GOBIN` could be used as well, but it also needs to be added to `$PATH`. Since `go env GOBIN` is not set and `$GOPATH/bin` is the default installation path it's just simpler to add the default path to `$PATH`.

**Comment by damccorm** [comment]
I think this should probably be resolved together with #12. Given [my most recent comment](https://github.com/actions/setup-go/issues/12#issuecomment-522593317) in that issue, are you ok with closing here and following up there?

**Comment by lmittmann** [comment]
@damccorm Let's track this issue here, as it seems like #12 is quite fuzzy.

**Comment by mvdan** [comment]
I think you're overthinking this. The official Go docker images simply hard-code `PATH`, as you can see here: https://github.com/docker-library/golang/blob/3a6407a6ff134ef6a0364ac061b0808f990ea14e/1.13-rc/alpine3.10/Dockerfile#L59-L60

Why not do the same? If anyone wants to set up a custom `GOPATH` or `GOBIN`, they can set up a custom `PATH` too. I'd prefer `PATH` to be simple and predictable.

**Comment by leighmcculloch** [comment]
You can avoid this issue by instead using the actions `container` param to run all the commands in the official `golang` Docker image. You can see what that looks like here:
https://github.com/stellar/go-xdr/blob/3aa3546/.github/workflows/build.yml

**Comment by mvdan** [comment]
@leighmcculloch I assume that won't work for testing on mac and windows, though, so fixing this bug is still very useful.

**Comment by sanemat** [comment]
I prefer this solution below. This works on windows, ubuntu, and mac.
```
    steps:
    - name: setup go
      uses: actions/setup-go@v1
      with:
        go-version: 1.x
    - name: setup env
      run: |
        echo "::set-env name=GOPATH::$(go env GOPATH)"
        echo "::add-path::$(go env GOPATH)/bin"
      shell: bash
    - name: checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
        path: src/github.com/${{ github.repository }}
```
https://stackoverflow.com/a/59242962/104080

**Comment by eduncan911** [comment]
@sanemat that still doesn't look right, as there is a bug in the checkout for that path.

To get it to work, I had to hardcode my path - which is unacceptable to me in a github action as things should be evaluated per ENVs and template vars:

```
  go-test:
    strategy:
      matrix:
        go-version: [1.7.x, 1.13.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: setup env
      shell: bash
      run: |
        echo "::set-env name=GOPATH::${{ github.workspace }}/go"
        echo "::add-path::$GOPATH/bin"
    - name: Install Go
      if: success()
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    - name: checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
        path: podcast/go/src/github.com/${{ github.repository }}
    - name: Run tests
      run: |
        go test -v -covermode=count 
```

Notice the `path: podcast/go/src/github.com/${{ github.repository }}`, which is prefixed with `podcast` because for some reason, $GITHUB_WORKSPACE is actually:

    /home/runner/work/podcast/podcast

Not what the `path` downloads to, which is:

    /home/runner/work/podcast

To make matters worse, you cannot access this above directory as there is no ENV var that sets it to be consumed.  So it has to be hardcoded.

**Comment by bryanmacfarlane** [comment]
hopefully we can get to this soon as part of v2-beta.

**Comment by eduncan911** [comment]
So, the devs on the checkout action told me there was a newer version  [@v2 that fixes the `WORKSPACE` issue](https://github.com/actions/checkout/issues/150).

This worked for all of my other actions, and I can remove the hardcoded `podcast` prefix I previously had to do in the `path` attribute above.

```
  go-test:
    strategy:
      matrix:
        go-version: [1.7.x, 1.13.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: setup env
      shell: bash
      run: |
        echo "::set-env name=GOPATH::${{ github.workspace }}/go"
        echo "::add-path::${{ github.workspace }}/go/bin"
    - name: Install Go
      if: success()
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    - name: checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
        path: go/src/github.com/${{ github.repository }}
    - name: Run tests
      shell: bash
      run: |
        cd $GOPATH/src/github.com/${{ github.repository }}
        go test -v -covermode=count 
```

I'm happy with this for now, as it's now abstracted and I can copy it across all of my repos with no hardcoding of the repo itself.

However, it still seems very verbose: having to set the GOPATH and BIN in other actions, as well as specifying BASH everywhere so I can pickup that GOPATH.
