### ISSUE TITLE
Retrieve go version from go.mod file

### ISSUE THREAD

**Issue by pantelis-karamolegkos** [actions/setup-go#174]
**Description:**
Instead of hard-coding the `go` version, the action could (optionally)

- search in the root of the project (or in any other configurable place) for a `go.mod` file
- extract and use the `go` version specified there.

**Justification:**
Justification or a use case for your proposal.

**Are you willing to submit a PR?**

**Comment by TMaYaD** [comment]
FWIW, this is the workaround I use:
```yaml
      - run: sed -En 's/^go[[:space:]]+([[:digit:].]+)$/GO_VERSION=\1/p' go.mod >> $GITHUB_ENV
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
```

**Comment by thetillhoff** [comment]
Thanks @TMaYaD, that helped me a lot!
Here's a slightly shorter version that IMO is a bit easier to understand:
```
      - run: sed -En 's/^go (.*)$/GO_VERSION=\1/p' go.mod >> $GITHUB_ENV
      - uses: actions/setup-go@v2
        with:
          go-version: "${{ env.GO_VERSION }}"
```

**Comment by prajwal-koirala-0000** [comment]
```
      - name: Get the current version of Go from project.
        run: GO_VERSION_FROM_PROJECT=$(cat go.mod | head -3 | tail -1 | cut -d' ' -f2)
      - name: Set up Go version ${GO_VERSION_FROM_PROJECT}
        uses: actions/setup-go@v2
        with:
          go-version: ${GO_VERSION_FROM_PROJECT}
```

**Comment by prajwal-koirala-0000** [comment]
``` yaml
      - name: Get the current version of Go from project.
        run: cat go.mod | head -3 | tail -1 | echo "GO_VERSION_FROM_PROJECT=$(cut -d' ' -f2)" >>${GITHUB_ENV}
      - name: Set up Go version "${{ env.GO_VERSION_FROM_PROJECT }}"
        uses: actions/setup-go@v2
        with:
          go-version: "${{ env.GO_VERSION_FROM_PROJECT }}"
```

I know about the shell check issue `SC2002` but since this is the easiest way to understand the code and performance isn't an issue, it will be fine.

**Comment by prajwal-koirala-0000** [comment]
# Linux
``` yaml
      - name: Get the system requirements.
        run: sudo apt-get install coreutils -y
      - name: Get the current version of Go from project.
        run: cat go.mod | head -3 | tail -1 | echo "GO_VERSION_FROM_PROJECT=$(cut -d' ' -f2)" >>${GITHUB_ENV}
      - name: Set up Go version "${{ env.GO_VERSION_FROM_PROJECT }}"
        uses: actions/setup-go@v2
        with:
          go-version: "${{ env.GO_VERSION_FROM_PROJECT }}"
        id: go
```
# MacOS
``` yaml
      - name: Get the system requirements.
        run: brew install coreutils
      - name: Get the current version of Go from project.
        run: cat go.mod | head -3 | tail -1 | echo "GO_VERSION_FROM_PROJECT=$(cut -d' ' -f2)" >>${GITHUB_ENV}
      - name: Set up Go version "${{ env.GO_VERSION_FROM_PROJECT }}"
        uses: actions/setup-go@v2
        with:
          go-version: "${{ env.GO_VERSION_FROM_PROJECT }}"
        id: go
```
# Windows
``` yaml
      - name: Get the current version of Go from project.
        run: type go.mod | select -Skip 2 -First 1 | %{ 'GO_VERSION_FROM_PROJECT={0}' -f ($_ -replace '^.+\s') } >>${GITHUB_ENV}
      - name: Set up Go version "${{ env.GO_VERSION_FROM_PROJECT }}"
        uses: actions/setup-go@v2
        with:
          go-version: "${{ env.GO_VERSION_FROM_PROJECT }}"
        id: go
```

I know about the shell check issue `SC2002` but since this is the easiest way to understand the code and performance isn't an issue, it will be fine.

**Comment by prajwal-koirala-0000** [comment]
### Linux
``` yaml
- name: Get the system requirements.
  run: sudo apt-get install coreutils -y
- name: Get the current version of Go from project.
  run: cat go.mod | head -3 | tail -1 | echo "GO_VERSION_FROM_PROJECT=$(cut -d' ' -f2)" >>${GITHUB_ENV}
- name: Set up Go version "${{ env.GO_VERSION_FROM_PROJECT }}"
  uses: actions/setup-go@v2
  with:
    go-version: "${{ env.GO_VERSION_FROM_PROJECT }}"
  id: go
```
### MacOS
``` yaml
- name: Get the system requirements.
  run: brew install coreutils
- name: Get the current version of Go from project.
  run: cat go.mod | head -3 | tail -1 | echo "GO_VERSION_FROM_PROJECT=$(cut -d' ' -f2)" >>${GITHUB_ENV}
- name: Set up Go version "${{ env.GO_VERSION_FROM_PROJECT }}"
  uses: actions/setup-go@v2
  with:
    go-version: "${{ env.GO_VERSION_FROM_PROJECT }}"
  id: go
```
### Windows
``` yaml
- name: Get the current version of Go from project.
  run: type go.mod | select -first 3 | select -last 1 | %{ 'GO_VERSION_FROM_PROJECT={1}' -f ($_ -split ' ') } >>$env:GITHUB_ENV
- name: Set up Go version "${{ env.GO_VERSION_FROM_PROJECT }}"
  uses: actions/setup-go@v2
  with:
    go-version: "${{ env.GO_VERSION_FROM_PROJECT }}"
  id: go
```
