### ISSUE TITLE
Installing Go 1.18 beta1 errors

### ISSUE THREAD

**Issue by leighmcculloch** [actions/setup-go#176]
**Description:**
When installing Go 1.18 beta1, the install fails to find the binary even though it has been released.

**Action version:**
`v2` which is at this time 331ce1d993939866bb63c32c6cbbfd48fa76fc57.

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**
Fails with both `go1.18beta1` and `go1.18.0-beta1`.

**Repro steps:**  
Demonstrated in this minimal PR: https://github.com/stellar/go/pull/4143

**Expected behavior:**
Install Go 1.18 beta1.

**Actual behavior:**

```
Run actions/setup-go@v2
  with:
    go-version: 1.18beta1
    stable: true
    token: ***
Setup go stable version spec 1.18beta1
Attempting to download 1.18beta1...
matching 1.18beta1...
Not found in manifest.  Falling back to download directly from Go
Error: Unable to find Go version '1.18beta1' for platform linux and architecture x64.
```

```
Run actions/setup-go@v2
  with:
    go-version: 1.18.0-beta1
    stable: true
    token: ***
Setup go stable version spec 1.18.0-beta1
Attempting to download 1.18.0-beta1...
matching 1.18.0-beta1...
Not found in manifest.  Falling back to download directly from Go
Error: Unable to find Go version '1.18.0-beta1' for platform linux and architecture x64.
```

**Comment by leighmcculloch** [comment]
Turns out I needed to set the stable param to false as well.

```yml
     - name: Set up Go
       uses: actions/setup-go@v2
       with:
         go-version: ${{ matrix.go }}
         stable: ${{ !contains(matrix.go, 'beta') }}
```
