### ISSUE TITLE
Add support for go 1.18

### ISSUE THREAD

**Issue by Prajwal-Koirala** [actions/setup-go#185]
Hello,
The title really says all there is to say about this.
- prajwal

**Comment by dmitry-shibanov** [comment]
Hello @Prajwal-Koirala. Thank you for your report. For now go 1.18 provides unstable versions. When it's released as a stable version, we'll update the go-versions [manifest file](https://github.com/actions/go-versions/blob/main/versions-manifest.json). If you want to use unstable versions now you can try using this snippet:
```
    - name: Setup go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18.0-beta1
        stable: false
```
