### ISSUE TITLE
Doesn't support go1.18beta1 or go1.18beta2 

### ISSUE THREAD

**Issue by yeqown** [actions/setup-go#190]
**Description:**
```yaml
go-version: '1.18-beta2'
```

setup failed, `'1.18.0-beta2'` failed too ~, I wonder dose it support go1.18 beta versions?

**Action version:**
actions/setup-go@v2

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [ ] Hosted
- [ ] Self-hosted

**Tools version:**
go1.18-beta2

**Repro steps:**  

specify go-version with `1.18-beta2`, then it failed

**Expected behavior:**
setup action success

**Actual behavior:**
setup action failed

**Comment by dmitry-shibanov** [comment]
Hello @yeqown. Thank you for your report. Could you please try to use this snippet:
```yml
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18.0-beta2
        stable: false
```
