### ISSUE TITLE
golang 1.18 support

### ISSUE THREAD

**Issue by pratikbin** [actions/setup-go#206]
**Description:**
Since 1.18 is GA now, need `go-version: 1.18.x`

**Comment by dmke** [comment]
Not sure if related, but `go-version: 1.x` also runs Go 1.17.7.

**Comment by arthurkushman** [comment]
I'm trying to run GitHub Actions after updating repo to `Go 1.18` version and `setup-go` to `v3` and it's go version to 1.18, also updated `checkout` to `@v3` in context of compatibility - the error  https://github.com/arthurkushman/pgo/runs/5618443803?check_suite_focus=true

What should I do to make GitHub Actions work with setup-go?

**Comment by marko-zivic-93** [comment]
Hello @pratikbin
Thank you very much for pointing this issue out!
The issue is fixed. 

In order to use version 1.18.x you can use the following yaml snippet:

```
steps:
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.18.0"
```
@pratikbin can you please confirm that the issue is fixed?
@arthurkushman can you please create a separate issue dedicated to the problem you are experiencing?

**Comment by pratikbin** [comment]
@marko-zivic-93 Yessir, It's working `go-version: "1.18"`

**Comment by vsafonkin** [comment]
@dmke, you can use `check-latest` option for it:
```yaml
- name: Setup Go environment
  uses: actions/setup-go@v3
  with:
    go-version: 1.*
    check-latest: true
```
<img width="914" alt="Screenshot 2022-03-25 at 12 05 34 PM" src="https://user-images.githubusercontent.com/7628945/160109968-93e5df3f-a415-4ba8-8ada-978c2cd06f87.png">
