### ISSUE TITLE
externally configured Go version for automation support

### ISSUE THREAD

**Issue by jmhodges** [actions/setup-go#23]
I've got a GitHub Action I wrote to update the Go versions in my various configuration files[1]. Especially, for my security projects, I'd like an auditable but automated way to keep the Go versions I use up to date. 

(Using a `.x` version number isn't enough because doing that wouldn't kick off new builds when a new version is released and it's difficult to audit when a new Go version was brought in.)

But, unfortunately (and totally understandably from a security perspective!), GitHub Actions can't modify integration configs. So, I've got a plan to keep my Go versions in a file outside of my workflow configs, have my workflows read in that file and use it for `go_version`, and then have my tool update that external file.

Would y'all be open to me posting a PR to make that an explicitly supported thing in setup-go? Say, reading a file in something like `.github/versions/go.yml` or similar?

[1] https://github.com/jmhodges/ensure-latest-go

**Comment by jmhodges** [comment]
My setup-go config now looks like:

```yml
    - name: Read Go versions
      run: echo "##[set-output name=go_version;]$(cat .github/versions/go)"
      id: go_versions
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ steps.go_versions.outputs.go_version }}
      id: go
```

Example PR that came from it: https://github.com/jmhodges/howsmyssl/pull/267

It'd be nice to get this baked in. The `cat` inside it means I can only support one version at a time (I believe) and with a more standard support, we could fix that

**Comment by radeksimko** [comment]
Having an option like this would also allow interoperability with [goenv](https://github.com/syndbg/goenv) which stores local version in `.go-version` file in the root of the repo.

```yml
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version-from-file: .go-version
```

Picking up the version implicitly from there would be even better, but I suppose that would be better job for a more scoped Action with goenv, rather than generic Go one?

At least it seems that there is no precedent for version managers in official `setup-language` Actions.

**Comment by bryanmacfarlane** [comment]
@jmhodges on the set output, note that you should use `::` syntax.  `##` was deprecated.  See here: https://github.com/actions/toolkit/blob/master/docs/commands.md

@radeksimko - nice idea.  Since go-version input is a string, I may just overload that and do special handling for the value `.go-version`

**Comment by jmhodges** [comment]
Unfortunately, that regex deal wouldn’t give us an auditable version. It’d pick up whatever was the latest version when it happened to run, instead of when told to bump it. There’d be no way to track the PR it came in, etc

**Comment by hazcod** [comment]
@jmhodges : how I do it is I extract the Go version to use out of my Docker containers, print it and put it in a GitHub Actions variable.

**Comment by hazcod** [comment]
For reference my GitHub Action as seen on [iron-go-project](https://github.com/ironpeakservices/iron-go-project):
```yaml
name: benchmark
on: pull_request

jobs:
  gobench:
    name: benchmarking
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v2
      -
        id: vars
        run: |
          echo ::set-output name=go_version::$(grep '^FROM go' .github/go/Dockerfile | cut -d ' ' -f 2 | cut -d ':' -f 2)
          echo "Using Go version ${{ steps.vars.outputs.go_version }}"
      -
        name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ steps.vars.outputs.go_version }}
```

My file `.github/go/Dockerfile`:
```
FROM golang:1.14.1
```

And keeping the file updated automatically in `.github/dependabot.yml`:
```yaml

version: 2
updates:
- package-ecosystem: docker
  directory: "/.github/go"
  schedule:
    interval: daily
    time: '04:00'
  open-pull-requests-limit: 10
  target-branch: dev
```

**Comment by ccremer** [comment]
I'm using this:
```yaml
jobs:
  dist:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Determine Go version from go.mod
      run: echo "GO_VERSION=$(grep "go 1." go.mod | cut -d " " -f 2)" >> $GITHUB_ENV
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GO_VERSION }}
```
So I only have to maintain go.mod. Only works if you don't need matrix builds ofc :)

But it would be nice if this action could do that on its own, e.g. have a property `go-mod-path: go.mod`
