### ISSUE TITLE
failed to install unstable 1.19 rc version

### ISSUE THREAD

**Issue by Trim21** [actions/setup-go#245]
**Description:**

1.19 unstable has been released in offical download page

https://go.dev/dl/#go1.19rc2

But I can't install it with v3 version

```yaml
jobs:
  "go118":
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go_version: ["~1.18", ">=1.19-rc.2"]
    steps:
      - uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: "${{ matrix.go_version }}"
          check-latest: true
          cache: true

      - run: go test -count=1 -v ./...
        working-directory: ./internal/test/go118
```

`"~1.18"` installed, but failed when tring to install `">=1.19-rc.2"`

I tried `go1.19rc2`, `1.19rc2`, `>=1.19-rc.1`, non of them are working.

**Action version:**
Specify the action version

v3

**Platform:**
- [X] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [X] Hosted
- [ ] Self-hosted

**Tools version:**

`1.19-rc.2`

**Repro steps:**  
A description with steps to reproduce the issue. If your have a public example or repo to share, please provide the link.

https://github.com/Trim21/go-phpserialize/runs/7318388125?check_suite_focus=true

go correctly installed

**Expected behavior:**
A description of what you expected to happen.

**Actual behavior:**
A description of what is actually happening.
