### ISSUE TITLE
Lint: no go files to analyze

### ISSUE THREAD

**Issue by Allenxuxu** [actions/setup-go#25]
![image](https://user-images.githubusercontent.com/20566897/67860383-a9719d80-fb58-11e9-9535-c4988b9e005b.png)

https://github.com/Allenxuxu/gev/commit/f2db4e59dde570e11cec55c44d4e599ffc5124c7/checks?check_suite_id=288024110

This is my workflows.yml

```
name: CI
on: [push,pull_request]
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-18.04
    steps:
    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go
    - name: Code
      uses: actions/checkout@v1
    - name: Intsall Golangci-lint 
      run: curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b . latest
    - name: Lint
      run: ./golangci-lint run ./... --skip-dirs benchmarks
      
  test:
    needs: Lint
    name: Unit Testing
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-10.14,ubuntu-18.04]
    steps:
    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go
    - name: Code
      uses: actions/checkout@v1
    - name: Go Get dependencies
      run: go get -v -t -d ./...
    - name: Go Test
      run: go test -v ./...
```
