### ISSUE TITLE
Document the fact that the golang project needs to be located at the working-directory

### ISSUE THREAD

**Issue by lil5** [actions/setup-go#256]
**Description:**
There is no documentation warning people that the location of the project is important as well.

**Justification:**
Pushed to `main` and received this:

```log
Error: Dependencies file is not found in /home/runner/work/user/project. Supported file pattern: go.sum
```

~~Adding the following should fix my issue~~, but had rather known about this beforehand

```yml
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.19"
        working-directory: ./server
```

This does not work either

```log
The workflow is not valid. .github/workflows/lint-v2.yml (Line: 30, Col: 9): Unexpected value 'working-directory'
```

**Are you willing to submit a PR?**
Yes, If people think it is okay to do so.
