### ISSUE TITLE
Configurable cache keys for GOMODCACHE and GOCACHE

### ISSUE THREAD

**Issue by AaronFriel** [actions/setup-go#262]
Hello folks!

I have a use case for configuring separate cache keys for GOMODCACHE and GOCACHE. The workflow linked below, for github.com/pulumi/pulumi, builds binaries across 6 target operating systems and architectures.

The current design of the cache results in all of these targets having the same cache key. The six jobs share a cache key for both caches, but only GOMODCACHE can be effectively shared across these builds.

## Current behavior, limitations

There is no workaround at this time to enable sharing of the GOMODCACHE.

This is a workaround we use to ensure that each job does not clobber one another's cache, for subsequent runs:

```yaml
      - name: Configure GitHub Cache Key
        env:
          CACHE_KEY: "${{ github.workflow }}-${{ runner.os }}-${{ runner.arch }}-${{ inputs.os }}-${{ inputs.arch }}"
        run: echo "$CACHE_KEY" > .gocache.tmp
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ inputs.go-version }}
          cache: true
          cache-dependency-path: |
            */go.sum
            .gocache.tmp
```

## Desired behavior

Two cache keys are used, one each for GOCACHE and GOMODCACHE. The former would automatically include `runner.os` and `runner.arch` as input material. An input would allow further specialization:

```yaml
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ inputs.go-version }}
          cache: true
          cache-dependency-path: '*/go.sum'
          gocache-key: ${{ runner.os }}-${{ runner.arch }}-${{ inputs.os }}-${{ inputs.arch }}
```

As the amount of data cached in our jobs is substantial, approximately half a gigabyte compressed, and the majority of this data is in a few GOMODCACHE dependencies such as `github.com/!azure/azure-sdk-for-go`, this would greatly improve our cache usage for pulumi/pulumi.
