### ISSUE TITLE
install failure on alpine

### ISSUE THREAD

**Issue by codefromthecrypt** [actions/setup-go#263]
**Description:**
`go: cannot find GOROOT directory: /usr/local/go` if 

**Action version:**
v3

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**
1.18.5

**Repro steps:** 

This is a simplified version of tinygo's linux.yml in https://github.com/tinygo-org/tinygo/pull/3140
```
    runs-on: ubuntu-latest
    container:
      image: alpine:3.16
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
          cache: true
```

**Expected behavior:**
I would expect it to not fail

**Actual behavior:**

```
Run actions/setup-go@v3
  with:
    go-version-file: go.mod
    cache: true
    check-latest: false
    token: ***
/usr/bin/docker exec  1a481a0e1e30def1ee993d1ce10f6afd67e2b044eca2e5f372682a6997f61b7a sh -c "cat /etc/*release | grep ^ID"
Setup go version spec 1.18
Found in cache @ /__t/go/1.18.5/x64
Added go to the path
go: cannot find GOROOT directory: /usr/local/go
Error: Command failed: go env GOPATH
go: cannot find GOROOT directory: /usr/local/go
```
