### ISSUE TITLE
Uses a different version than specified

### ISSUE THREAD

**Issue by arjendevos** [actions/setup-go#274]
**Description:**
When using actions/setup-go@v3 with version 1.18.2, the logs tell me it is trying to download 1.18.2 but it is actually downloading 1.19.2.

![Screenshot 2022-10-10 at 15 30 07](https://user-images.githubusercontent.com/67794681/194877740-10855845-032d-4def-a687-5277e0a44277.png)

**Action version:**
v3

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [ ] Hosted
- [x] Self-hosted

**Tools version:**
1.18.2

**Repro steps:**  
Create a go project with a github workflow. 
Add this to your yml file:
```
 - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: "^1.18.2" # The Go version to download (if necessary) and use.
```

**Expected behavior:**
We want to use go version 1.18.2.

**Actual behavior:**
We get go version 1.19.2
