### ISSUE TITLE
Specifying go-version 1.19 defaults to 1.19.2, as opposed to the actual major version 1.19

### ISSUE THREAD

**Issue by sebastian-quintero** [actions/setup-go#285]
**Description:**
I have specified an action with the specific version `1.19`. I want that specific major version. However, the action is getting `1.19.2`, which is not what I want. You can see a screenshot here.

<img width="1053" alt="image" src="https://user-images.githubusercontent.com/42215971/199359127-bf0d46f7-c034-4e2f-808e-0c09c89002b5.png">

**Action version:**
v3

**Platform:**
- [x] Ubuntu
- [x] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**
1.19

**Repro steps:**  
Set up an action with the following characteristics:

```yml
 - name: set up go 1.19
    uses: actions/setup-go@v3
    with:
      go-version: 1.19
      check-latest: false
      cache: false
    id: go
```

**Expected behavior:**
I expect the action to configure `1.19`, not `1.19.2`.

**Actual behavior:**
The action is configuring `1.19.2`.
