### ISSUE TITLE
use `check-latest: true`  but it doesn't work

### ISSUE THREAD

**Issue by li-jin-gou** [actions/setup-go#287]
**Description:**
I want to set check-latest to get go version 1.19.3, but it still gets version 1.19.2
this is pr: https://github.com/gofiber/fiber/pull/2197

**Action version:**

V3 

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**

**Repro steps:**  
```
on: [push, pull_request_target]
name: Vulnerability Check
jobs:
  Security:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
        check-latest: true
    - name: Fetch Repository
      uses: actions/checkout@v3
    - name: Install Govulncheck
      run: |
          export GO111MODULE=on
          export PATH=${PATH}:`go env GOPATH`/bin
          go install golang.org/x/vuln/cmd/govulncheck@latest
    - name: Run Govulncheck
      run: "`go env GOPATH`/bin/govulncheck ./..."
```

**Expected behavior:**

Go version equal to 1.19.3

**Actual behavior:**

Go version equal to 1.19.2
