### ISSUE TITLE
 error: command not found: goimports

### ISSUE THREAD

**Issue by danbryan** [actions/setup-go#289]
**Description:**
I am getting an error of `go imports command not found` when using this action.  I am able to to other go commands like:
```
go build
go mod
go vet
```

**Action version:**
act version 0.2.31

**Repro steps:**  
Using this workflow
```
name: test
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
  push:
    branches:
      - main

env:
  GO_VERSION: '>=1.19.0'

jobs:

  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3.3.1
        with:
          go-version: ${{ env.GO_VERSION }}
      - run: go version
      - name: Run Revive Action by pulling pre-built image
        uses: docker://morphy/revive-action:v2.4.1
      - uses: pre-commit/action@v3.0.0
```
and this .pre-commit-config.yaml
```
repos:
  - repo: https://github.com/tekwizely/pre-commit-golang
    rev: v1.0.0-rc.1
    hooks:
      # Go Build
      -   id: go-build-repo-mod
      # Go Mod Tidy
      -   id: go-mod-tidy-repo
      # Go Vet
      -   id: go-vet-repo-mod
      # Style
      -   id: go-imports-repo
      -   id: golangci-lint-repo-mod
          args: [-E,whitespace,-E,gocritic,-E,revive,-E,gosec,-E,gofmt]
```
**Expected behavior:**
goimports would run

**Actual behavior:**
command not found: goimports

**Example of Act output:**
```
[test/pre-commit]   🐳  docker exec cmd=[bash --noprofile --norc -e -o pipefail /var/run/act/workflow/4-composite-3.sh] user= workdir=
| [INFO] Initializing environment for https://github.com/tekwizely/pre-commit-golang.
| go-build-repo-mod........................................................Passed
| go-mod-tidy-repo.........................................................Passed
| go-vet-repo-mod..........................................................Passed
| go-imports-repo..........................................................Failed
| - hook id: go-imports-repo
| - exit code: 1
| 
| error: command not found: goimports
| 
| golangci-lint-repo-mod...................................................Failed
| - hook id: golangci-lint-repo-mod
| - exit code: 1
| 
| error: command not found: golangci-lint
```

However when using my local box with pre-commit i get
```
pre-commit run --all-files
[INFO] Initializing environment for https://github.com/tekwizely/pre-commit-golang.
go-build-repo-mod........................................................Passed
go-mod-tidy-repo.........................................................Passed
go-vet-repo-mod..........................................................Passed
go-imports-repo..........................................................Passed
golangci-lint-repo-mod...................................................Passed
```

**Comment by danbryan** [comment]
This seems to resolve my issue, but would love to see imports inclduing in the default setup-go.
```
jobs:

  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3.3.1
        with:
          go-version: ${{ env.GO_VERSION }}
      - run: go version
      - run: go install golang.org/x/tools/cmd/goimports@latest
      - run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -  -b $(go env GOPATH)/bin v1.49.0
      - run: echo "PATH=$PATH:/home/runner/go/bin" >> $GITHUB_ENV
      - uses: pre-commit/action@v3.0.0
```
