### ISSUE TITLE
Caching doesn't work with cross-compiling

### ISSUE THREAD

**Issue by barrettj12** [actions/setup-go#298]
**Description:**
When using this action with `cache: true`, the cache doesn't seem to work for cross-compiling. Our workflow is essentially:
```yaml
    - uses: actions/setup-go@v3
      with:
        cache: true
    - run: GOOS=... GOARCH=... go install ...
```
We get a nice speed-up when the GOOS and GOARCH match the OS/arch of the runner. If they don't match, there is no speedup of the build process. See these two action runs:
https://github.com/barrettj12/juju/actions/runs/3616873783/attempts/1
https://github.com/barrettj12/juju/actions/runs/3616873783/attempts/2

I suspect this is because the action only caches build artifacts for the runner's OS and arch.

**Action version:**
v3

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**

Go 1.19
