### ISSUE TITLE
Cache doesn't work with Go 1.14

### ISSUE THREAD

**Issue by barrettj12** [actions/setup-go#304]
**Description:**
When I use this action with Go 1.14 and the cache enabled, it fails with
```
Error: Could not get cache folder paths.
```

**Action version:**
v3

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**

Go 1.14

**Repro steps:**  
Run the following step:
```yaml
      uses: actions/setup-go@v3
      with:
        go-version: 1.14
        cache: true
```

See sample test run here:
https://github.com/canonical/pebble/actions/runs/3681163227/jobs/6227686103
