### ISSUE TITLE
Failed to download version 1.17: Error: The process failed with exit code 1

### ISSUE THREAD

**Issue by ImAbhishekTomar** [actions/setup-go#310]
I am running my action on GIHUB enterprises, but most of the time "actions/setup-go@v3" this action is failing with the below error. Please help.

**ERRROR**

```
Run actions/setup-go@v3
  with:
    token: ***
    go-version-file: go.mod
    cache: true
    check-latest: false
  
Setup go version spec 1.17
Attempting to download 1.17...
API rate limit exceeded for 198.***.***.175. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
Falling back to download directly from Go
Install from dist
Acquiring go1.17.13 from https://storage.googleapis.com/golang/go1.17.13.windows-amd64.zip
Extracting Go...
C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command "$ErrorActionPreference = 'Stop' ; try { Add-Type -AssemblyName System.IO.Compression.FileSystem } catch { } ; if ((Get-Command -Name Expand-Archive -Module Microsoft.PowerShell.Archive -ErrorAction Ignore)) { Expand-Archive -LiteralPath 'D:\ghes\runner4\actions-runner\_work\_temp\68395d27-4a73-45bf-baf1-81ff3c5fd152' -DestinationPath 'D:\ghes\runner4\actions-runner\_work\_temp\ac266d89-c280-4318-9210-5d51b4a977e8' -Force } else {[System.IO.Compression.ZipFile]::ExtractToDirectory('D:\ghes\runner4\actions-runner\_work\_temp\68395d27-4a73-45bf-baf1-81ff3c5fd152', 'D:\ghes\runner4\actions-runner\_work\_temp\ac266d89-c280-4318-9210-5d51b4a977e8', $true) }"
Expand-Archive :  is not a supported archive file format. .zip is the only supported archive file format.
At line:1 char:210
+ ...  Ignore)) { Expand-Archive -LiteralPath 'D:\ghes\runner4\actions-runn ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:String) [Expand-Archive], IOException
    + FullyQualifiedErrorId : NotSupportedArchiveFileExtension,Expand-Archive
Error: Failed to download version 1.17: Error: The process 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe' failed with exit code 1
```
  

**Workflow File**

```
name: Build & Deployment Action #v01
on:
  push:
    branches: ["master"]
jobs:
  build:
    runs-on: [self-hosted]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Go
        continue-on-error: false
        uses: actions/setup-go@v3
        with:
          token: ${{ secrets.GH_ABC_ACTION_TOKEN }}
          go-version-file: "go.mod"
          cache: true
      - run: go version
```
