### ISSUE TITLE
go1.20rc2 has been released but setup-go can't find it

### ISSUE THREAD

**Issue by ncw** [actions/setup-go#318]
**Description:**

I expected this to install go1.20rc2 which was released a few days ago

```
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20-rc.2'
          check-latest: true
```

However it produces this error instead

```
Unable to find Go version '1.20-rc.2' for platform linux and architecture x64.
```

**Action version:**

v3

**Platform:**
- [x] Ubuntu
- [x] macOS
- [x] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**

'1.20-rc.2'

**Repro steps:**  

See: https://github.com/rclone/rclone/actions/runs/3902313635
