### ISSUE TITLE
`go-version: 1.20` installs go 1.2.2

### ISSUE THREAD

**Issue by Akaame** [actions/setup-go#328]
**Description:**

```yaml
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20
          check-latest: true
```

Installs Go 1.2.2 instead of Go 1.20.0 unless you explicitly assign `go-version: 1.20.0` (notice the explicit patch version at the end).

**Action version:**
See the yaml above

**Platform:**
- [X] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [X] Hosted
- [ ] Self-hosted

**Tools version:**
go 1.20

**Repro steps:**  
Execute `setup-go` action with `go-version: 1.20`

**Expected behavior:**
1.20.0 to be installed

**Actual behavior:**
go version reports 1.2.2

**Comment by panticmilos** [comment]
hi @Akaame, we had a similar issue today reported, and the solution was to provide the `go-version: '1.20'`  instead of `go-version: 1.20.` Can you confirm this solution is working for you? You can check this https://github.com/actions/setup-python/issues/160#issuecomment-724485470 for more detailed explanation

**Comment by frantjc** [comment]
> hi @Akaame, we had a similar issue today reported, and the solution was to provide the `go-version: '1.20'` instead of `go-version: 1.20.` Can you confirm this solution is working for you? You can check this [actions/setup-python#160 (comment)](https://github.com/actions/setup-python/issues/160#issuecomment-724485470) for more detailed explanation

I can confirm that

```yml
- use: actions/setup-go@v3
  with:
    go-version: 1.20
```

does not work for me while

```yml
- use: actions/setup-go@v3
  with:
    go-version: '1.20'
```

does work using the same setup as @Akaame
