### ISSUE TITLE
Partial version numbers don't work correctly.

### ISSUE THREAD

**Issue by sazzer** [actions/setup-go#344]
**Description:**
I've just tried to configure this action to install Go "1.20" - in the hopes that this would then actually install the latest 1.20.x without my needing to be exact. However, what it actually did was install 1.2 instead, which then obviously failed to run the CI pipeline.

**Action version:**
`actions/setup-go@v3`

**Platform:**
- [X] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [X] Hosted
- [ ] Self-hosted

**Tools version:**
N/A

**Repro steps:**  
The following Github Actions script:
```
name: CI

on:
  push:

env:
  GO_VERSION: 1.20

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
```

**Expected behavior:**
Ideal would be the latest version of 1.20.x. Acceptable would have been 1.20.0.

**Actual behavior:**
```
Setup go version spec 1.2
Attempting to download 1.2...
matching 1.2...
Not found in manifest.  Falling back to download directly from Go
Install from dist
Acquiring go1.2.2 from https://storage.googleapis.com/golang/go1.2.2.linux-amd64.tar.gz
Extracting Go...
/usr/bin/tar xz --warning=no-unknown-keyword --overwrite -C /home/runner/work/_temp/edf7e45b-ea7a-4f98-ab2e-5d9a2ca844a2 -f /home/runner/work/_temp/6725d6de-8678-4dba-bac9-bae7d7ef6599
Successfully extracted go to /home/runner/work/_temp/edf7e45b-ea7a-4f98-ab2e-5d9a2ca844a2
Adding to the cache ...
Successfully cached go to /opt/hostedtoolcache/go/1.2.2/x64
Added go to the path
Setting GOROOT for Go version < 1.9
Successfully set up Go version 1.2
go version go1.2.2 linux/amd64
```
