### ISSUE TITLE
Unable to find Go version X for platform linux and architecture x86

### ISSUE THREAD

**Issue by loshz** [actions/setup-go#347]
**Description:**
Passing the `x86` architecture for Linux always results in an error regardless of Go version.

**Action version:**
v3.5.0

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**
1.19/1.20

**Repro steps:**  
Using the following config, I expected to see the x86 architecture downloaded:
```yaml
jobs:
  go-test:
    strategy:
      matrix:
        go: ['1.19', '1.20']
        arch: ['x86', 'x64']
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}
        architecture: ${{ matrix.arch }}
        cache: true
    - run: go test ./...
````

**Expected behavior:**
The expected versions do exist as [Go releases](https://go.dev/dl/):
| File name | Kind | OS | Arch | Size | SHA256 Checksum |
|---|---|---|---|---|---|
| [go1.20.2.linux-386.tar.gz](https://go.dev/dl/go1.20.2.linux-386.tar.gz) | Archive | Linux | x86 | 96MB | ee240ed33ae57504c41f04c12236aeaa17fbeb6ea9fcd096cd9dc7a89d10d4db |
| [go1.19.7.linux-386.tar.gz](https://go.dev/dl/go1.19.7.linux-386.tar.gz) | Archive | Linux | x86 | 115MB | 5057ef6c1d221a9fe67e99c73b0deaa5bffc93bb854c11ce4b64a04f288ad20a |

**Actual behavior:**
Go 1.19:
```
Run actions/setup-go@v3
  with:
    go-version: 1.19
    architecture: x86
    cache: true
    check-latest: false
    token: ***
Setup go version spec 1.19
Attempting to download 1.19...
matching 1.19...
Not found in manifest.  Falling back to download directly from Go
Error: Unable to find Go version '1.19' for platform linux and architecture x86.
```

Go 1.20:
```
Run actions/setup-go@v3
  with:
    go-version: 1.20
    architecture: x86
    cache: true
    check-latest: false
    token: ***
Setup go version spec 1.20
Attempting to download 1.20...
matching 1.20...
Not found in manifest.  Falling back to download directly from Go
Error: Unable to find Go version '1.20' for platform linux and architecture x86.
```
