### ISSUE TITLE
get go v1.2 instead of v1.20

### ISSUE THREAD

**Issue by PascalBourdier** [actions/setup-go#355]
**Description:**
setup-go get the wrong version (go 1.2) when I try to use go 1.20

my config is:
```yaml
jobs:
  build:
    name: app-taas tests
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20
        id: go
```

this is the output:
```shell
Run actions/setup-go@v3
  with:
    go-version: 1.2
    check-latest: false
    token: ***
    cache: false
Setup go version spec 1.2
Attempting to download 1.2...
matching 1.2...
Not found in manifest.  Falling back to download directly from Go
Install from dist
Acquiring go1.2.2 from https://storage.googleapis.com/golang/go1.2.2.linux-amd64.tar.gz
Extracting Go...
```

**Action version:**
v3

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**
1.20

**Repro steps:**  
It is possible to reproduce the problem with this config:
```yaml
jobs:
  build:
    name: app-taas tests
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20
        id: go
```

**Expected behavior:**
```shell
Run actions/setup-go@v3
  with:
    go-version: 1.20
    check-latest: false
    token: ***
    cache: false
Setup go version spec 1.20
Attempting to download 1.20...
matching 1.20...
Not found in manifest.  Falling back to download directly from Go
Install from dist
Acquiring go1.20.2 from https://storage.googleapis.com/golang/go1.20.2.linux-amd64.tar.gz
Extracting Go...
```

**Actual behavior:**
```shell
Run actions/setup-go@v3
  with:
    go-version: 1.2
    check-latest: false
    token: ***
    cache: false
Setup go version spec 1.2
Attempting to download 1.2...
matching 1.2...
Not found in manifest.  Falling back to download directly from Go
Install from dist
Acquiring go1.2.2 from https://storage.googleapis.com/golang/go1.2.2.linux-amd64.tar.gz
Extracting Go...
```

**Comment by PascalBourdier** [comment]
a work around is to use the minor go 1.20 version (1.20.2 for I.E):
```yaml
jobs:
  build:
    name: app-taas tests
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.2
        id: go
```

**Comment by PascalBourdier** [comment]
yaml is the guilty, we have add double quotes:
```
jobs:
  build:
    name: app-taas tests
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"
        id: go
```
