### ISSUE TITLE
Wrong go version

### ISSUE THREAD

**Issue by ismdeep** [actions/setup-go#356]
```
- name: Setup Go
  uses: actions/setup-go@v4
  with:
    go-version: 1.20
```

But got go v1.2

See: https://github.com/ismdeep/doraemon/actions/runs/4444825467/jobs/7803380963
