### ISSUE TITLE
When `go version 1.20` is specified, it is interpreted as `1.2`

### ISSUE THREAD

**Issue by saitotqr** [actions/setup-go#361]
**Description:**
When `go version 1.20` is specified, it is interpreted as `1.2`

**Action version:**
setup-go@v4

**Platform:**
- [x]] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Repro steps:**  

```
jobs:
  foobar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20
          cache: true
          cache-dependency-path: go.sum
```

**Expected behavior:**
I expect `go-version: 1.20` to be set up.

**Actual behavior:**
`go-version: 1.2` has been set.
```
Run actions/setup-go@v4
  with:
    go-version: 1.2
    cache: true
    cache-dependency-path: go.sum
    check-latest: false
    token: ***
Setup go version spec 1.2
Attempting to download 1.2...
matching 1.2...
Not found in manifest.  Falling back to download directly from Go
Install from dist
Acquiring go1.2.2 from https://storage.googleapis.com/golang/go1.2.2.linux-amd64.tar.gz
Extracting Go...
/usr/bin/tar xz --warning=no-unknown-keyword --overwrite -C /home/runner/work/_temp/2c5cee7e-9571-43bb-81e9-b84dbfa750f8 -f /home/runner/work/_temp/2eeb162d-e2fc-4f1b-b00a-21466e4c9042
Successfully extracted go to /home/runner/work/_temp/2c5cee7e-9571-43bb-81e9-b84dbfa750f8
Adding to the cache ...
Successfully cached go to /opt/hostedtoolcache/go/1.2.2/x64
Added go to the path
Setting GOROOT for Go version < 1.9
Successfully set up Go version 1.2
/opt/hostedtoolcache/go/1.2.2/x64/bin/go env GOMODCACHE
/opt/hostedtoolcache/go/1.2.2/x64/bin/go env GOCACHE

:

Run go run main.go
Error: main.go:4:2: cannot find package "context" in any of:
	/opt/hostedtoolcache/go/1.2.2/x64/src/pkg/context (from $GOROOT)
	($GOPATH not set)
```

**Workaround:**
If I specified up to a minor version, it works fine.
```
     - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.2
```
