### ISSUE TITLE
`go-version: ">=1.20"` with `check-latest: true` does not resolve to 1.20.5

### ISSUE THREAD

**Issue by silverwind** [actions/setup-go#384]
go1.20.5 was released on 2023-06-06, but this action does not find it, even with `check-latest` enabled. This is problematic for us because we have [govulncheck](https://pkg.go.dev/golang.org/x/vuln/cmd/govulncheck) in the pipeline and all builds fail because of vulnerabilities in go1.20.4.

````yaml
- uses: actions/setup-go@v4
  with:
    go-version: ">=1.20"
    check-latest: true
````

[Run output](https://github.com/go-gitea/gitea/actions/runs/5219192752/jobs/9420752752?pr=25167):

````
Run actions/setup-go@v4
Setup go version spec >=1.20
Attempting to resolve the latest version from the manifest...
matching >=1.20...
Resolved as '1.20.4'
Found in cache @ /opt/hostedtoolcache/go/1.20.4/x64
Added go to the path
Successfully set up Go version >=1.20
````
