### ISSUE TITLE
Get a error when go-version 1.21rc2 is required

### ISSUE THREAD

**Issue by salamandra19** [actions/setup-go#389]
**Description:**
I got a error, when I choose to setup go version `1.21rc2` in workflow.

![Снимок экрана от 2023-06-25 16-54-17](https://github.com/actions/setup-go/assets/20011440/c38ac6d6-dd61-49ad-b5b1-6bca8f56e135)

Both ways `1.21rc2` and `^1.21rc2` give the same result.
Why is it not working???

**Action version:**
actions/setup-go@v3

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**
go@1.21rc2

**Repro steps:**  
`.github/workflows/CI&CD.yml`
```
jobs:

  test:
    runs-on: 'ubuntu-latest'
    ...
        go:
          - '1.21rc2'
```

**Expected behavior:**
Download go version 1.21rc2

**Actual behavior:**
Get error `Unable to find Go version '1.21rc2' for platform linux and architecture x64.`
