### ISSUE TITLE
Add support for restoring from partial cache match

### ISSUE THREAD

**Issue by artuross** [actions/setup-go#404]
**Description:**
Currently, it seems that this action only restores cache **if** the cache key is matched exactly (`go.mod` and `go.sum` haven't changed).

**Justification:**
Typically, when updating dependencies, only some dependencies will be updated. With current version, it means that whenever a dependency is updated, the cache is not used and therefore all packages must be fetched. In my view, this is suboptimal.

I think there should be a setting to enable this behavior.

**Are you willing to submit a PR?**
Yes.

**Comment by dusan-trickovic** [comment]
Hello, @artuross ! Thank you for the suggestion, we will investigate it :)

**Comment by v-priya-kinthali** [comment]
Hello @artuross👋,
Thank you for the suggestion! You're right that setup-go's built-in caching uses an exact-match key based on `go.mod` (or `go.sum` if configured via `cache-dependency-path`), with no partial/prefix restore keys, so any dependency change results in a full cache miss by design.
However, adding this would introduce additional complexity and would be inconsistent with how caching is handled across other setup-* actions (e.g., [actions/setup-node](https://github.com/actions/setup-node), [actions/setup-python](https://github.com/actions/setup-python)), which also rely on exact-match keys for their built-in cache support.
For advanced caching needs, we recommend using [actions/cache](https://github.com/actions/cache) directly, which supports partial/prefix restore keys. You can disable the setup-go's built-in cache (`cache: false`) and manage caching as shown below:
```yaml
- uses: actions/setup-go@v6
  with:
    go-version: '1.22'
    cache: false

- uses: actions/cache@v5
  with:
    path: |
      ~/go/pkg/mod
      ~/.cache/go-build
    key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
    restore-keys: |
      ${{ runner.os }}-go-
```
Relevant docs:
[Caching dependencies to speed up workflows](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/caching-dependencies-to-speed-up-workflows)
[actions/cache – Go modules example](https://github.com/actions/cache/blob/main/examples.md#go---modules)

Please feel free to reach out if you have any further concerns. Thank you!
