### ISSUE TITLE
Need 1.20.7 - consider automating go-versions availability?

### ISSUE THREAD

**Issue by ldemailly** [actions/setup-go#405]
Need check-latest to pick up 1.20.7 

my CI is failing because of govulncheck flagging the security issue in 1.20.6

_Originally posted by @ldemailly in https://github.com/actions/setup-go/issues/373#issuecomment-1663152355_

**Comment by gaby** [comment]
@ldemailly This seems to be a recurring issue everytime there's a new go release. It doesn't help that the Golang team forces you to use the latest `Go` to use `govulncheck`.  This is my CI setup

```yaml
jobs:
  govulncheck-check:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
    - name: Fetch Repository
      uses: actions/checkout@v3
    - name: Install Go
      uses: actions/setup-go@v4
      with:
        go-version: 'stable'
        check-latest: true
        cache: false
    - name: Install Govulncheck
      run: go install golang.org/x/vuln/cmd/govulncheck@latest
    - name: Run govulncheck
      run: govulncheck ./...
```

I thought that using `check-latest` and `cache` were going to mitigate this issue, but the Go version is hardcoded somewhere.
