### ISSUE TITLE
Tar errors on cache restore after toolchain installation

### ISSUE THREAD

**Issue by matthewhughes-uw** [actions/setup-go#424]
**Description:**

When the version of Go in the `go` directive of `go.mod` is different from the version in the `toolchain` directive there is a cache conflict which causes errors on cache extraction.

Note: I think this is related to, but different from https://github.com/actions/setup-go/issues/403 since that appears to  be covering the situation where some other tool is also working on the cache, but this issue is purely for the action running on a hosted runner without any additional changes to the environment etc.

**Action version:**

`actions/setup-go@v4`

**Platform:**
- [x] Ubuntu
- [ ] macOS (untested)
- [ ] Windows (untested)

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**

* `go 1.21.0`
* `toolchain go1.21.1`

**Repro steps:**  

See repo https://github.com/matthewhughes-uw/setup-go-test/, very basic repo with a single workflow that just runs this action (https://github.com/matthewhughes-uw/setup-go-test/blob/main/.github/workflows/go.yaml):

First run of the action https://github.com/matthewhughes-uw/setup-go-test/actions/runs/6195831453/job/16821285537

* Installs Go 1.21.0 (version detected from `go-version-file`
* Go detects toolchain and performs a toolchain install of Go 1.21.1 (see output `go: downloading go1.21.1 (linux/amd64)`)
* This places some files under `../../../go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.1.linux-amd64`
* Finds no existing cache, doesn't try to extract anything
* Caches  `/home/runner/go/pkg/mod` (which contains the files above) and `/home/runner/.cache/go-build`

Second run of the action https://github.com/matthewhughes-uw/setup-go-test/actions/runs/6195844389/job/16821321968

* First two steps as above
* Finds an existing cache, attempts to extract it, but because of the toolchain installation step files under `../../../go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.1.linux-amd64` are already present on the machine, causing errors from `tar`

**Expected behavior:**

Caching of the toolchain is handled gracefully, no errors between runs that don't contain any extra caching logic outside of what the action provides by default

**Actual behavior:**

Errors on cache extraction (see repro steps)

**Comment by dsame** [comment]
Hello @matthewhughes-uw , thank you for the input. We are starting to investigate the problem.

**Comment by thall** [comment]
> Hello @matthewhughes-uw , thank you for the input. We are starting to investigate the problem.

do you have any updates around this to share?

**Comment by HaraldNordgren** [comment]
@matthewhughes-uw Any updates on this? After updating to Go version:

```diff
--- a/go.mod
+++ b/go.mod
@@ -1,6 +1,8 @@
 module github.com/company/repo

-go 1.20
+go 1.21.1
+
+toolchain go1.21.6

 require (
```

We start having these warnings in the build:

```
/usr/bin/tar: ../../../go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.6.linux-amd64/lib/time/mkzip.go: Cannot open: File exists
/usr/bin/tar: ../../../go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.6.linux-amd64/lib/time/zoneinfo.zip: Cannot open: File exists
/usr/bin/tar: ../../../go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.6.linux-amd64/lib/time/README: Cannot open: File exists
...
```

**Comment by matthewhughes-uw** [comment]
> The issue seems to be caused by the setup-go being confused about the difference in "Go" version and the newly introduced "Toolchain" version.
> 
>     * It first downloads and caches 1.21.1
>     * Then tries to download 1.21.6 as toolchain version
>     * But for some reason this 1.21.6 download defaults back to 1.21.1, which it tries to download and cache
>     * And boom... it 1.21.1 already exists in the cache from the first step! 🧨

Note: the toolchain download is not done by `setup-go`, it's done by `Go` itself, e.g.

```go.mod
module example.com/my-mod

go 1.21.0

toolchain go1.21.1
```

Then if you try to run a `go` command using a version that doesn't match the `toolchain` the toolchain will be downloaded (creating new caches to ensure we download the new toolchain, and not just silently use an existing one):

```
$ mkdir gocache gomodcache
$ GOCACHE=$PWD/gocache GOMODCACHE=$PWD/gomodcache/ go1.21.0 env
go: downloading go1.21.1 (linux/amd64)
```

So unless `setup-go` is configured to use the go version (or perhaps, any newer version) specified in the `toolchain` directive then there will be this download. `setup-go` then continues to use the version it was configured with to run any future `go` commands (which may just invoke the toolchain version in the background)

**Comment by HaraldNordgren** [comment]
@matthewhughes-uw That makes sense. What I don't understand is why Go on the second download defaults back from downloading 1.21.6 to instead getting 1.21.1 again. Because if this didn't happen, then there would be no cache problem.

How I solved it for now is to upgrade locally using 'go get go 1.21.6', which then removes the toolchain line altogether since Go and Toolchain versions are now the same. Then the caching issue does not appear.

**Comment by spencerschrock** [comment]
One way of avoiding this could be if `actions/setup-go` had a way of reading the toolchain directive instead of the go directive. Although it's still useful to test against the minimum version specified by the go directive, so I don't think changing the behavior of `go-version-file` is a good solution.

You could do your own toolchain version parsing in an earlier step, and set an env var or something:
```
uses: actions/setup-go@v5
with:
    go-version: ${{ env.GO_VERSION }}
```

**Comment by lukeed** [comment]
For those finding this issue, the current workaround is to just ensure that your `with/go-version` value **exactly** matches the version specified in `go.mod`

```go
// go.mod
go 1.22.2
```
```yml
# workflows/ci.yml
- uses: actions/setup-go@v5
  with:
    go-version: 1.22.2
```

**Comment by matthewhughes-uw** [comment]
> For those finding this issue, the current workaround is to just ensure that your `with/go-version` value **exactly** matches the version specified in `go.mod`

You could also set the `GOTOOLCHAIN` env var to `local`:

```yaml
    - name: Configure env for toolchain ignore
      shell: bash
      run: echo "GOTOOLCHAIN=local" >> "$GITHUB_ENV"
    - name: Setup Go
      uses: actions/setup-go@v5
```

see https://github.com/utilitywarehouse/go-actions/pull/15 for more details

**Comment by timandy** [comment]
The same issue for me.  Only go1.23 has the problem.

https://github.com/timandy/gohack/actions/runs/10399737890

![image](https://github.com/user-attachments/assets/4474959b-9a50-4b95-ae71-b6112628caa8)

**Comment by erikburt** [comment]
I'll chime in here to bump this thread, explain my issue, and a solution.

#### Situation:

1. We had a go and different toolchain version specified in our go.mod.
2. We had `cache: false` when calling this action.
3. We were caching go modules separately for when installing/building our projects

#### Problem:

1. Installing the go version (and not the toolchain) with this action
2. Running a go command would then cache the toolchain's modules
3. Running actions/cache on our go mod cache directory would
    - Saving: Caches the toolchain's modules 
    - Restore: Attempt to extract the toolchain's modules over a directory that already contained them (The cause of the errors)

#### Solutions:

I think both of the solutions I've shown here are rather hacky and this action should support installing the toolchain version instead.

<details><summary>Solution 1: Installing the toolchain version if it exists</summary>
<p>

```yaml
    - name: Get Go Version
      shell: bash
      id: go-version
      run: |
        version=$(sed -ne '/^toolchain /s/^toolchain go//p' ${{ inputs.go-version-file }})
        if [ -z "$version" ]; then
          version=$(sed -ne '/^go /s/^go //p' ${{ inputs.go-version-file }})
          echo "Toolchain version not found in ${{ inputs.go-version-file }}, using go directive instead."
        fi
        echo "Go Version: $version"
        echo "version=$version" >> "$GITHUB_OUTPUT"
    - name: Set up Go
      uses: actions/setup-go@v5.0.2
      with:
        go-version: ${{ steps.go-version.outputs.version }}
        cache: false
        check-latest: true
```

Full change here: [fix: install toolchain version smartcontractkit/chainlink#15645](https://github.com/smartcontractkit/chainlink/pull/15645)

</p>
</details> 


<details><summary>Solution 2: Suppressing tar errors with env var</summary>
<p>

```yaml
    - name: Setup tar default options
      shell: bash
      # Do not overwrite existing files when extracting files from a cache archive.
      # Since actions/cache does not support this option, we set it here as a default.
      run: echo "TAR_OPTIONS=--skip-old-files" >> $GITHUB_ENV
```

</p>
</details>
