### ISSUE TITLE
caches grow unbounded

### ISSUE THREAD

**Issue by schmidtw** [actions/setup-go#447]
**Description:**
In a Github Enterprise account the caches are growing in an unbounded manor.  I don't see this problem on open source Github accounts.

![image](https://github.com/actions/setup-go/assets/698825/e236d723-1e6b-4107-8273-3fc4ddaa0d40)

**Action version:**
`actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0`

**Platform:**
- [X] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**
1.21.5

**Repro steps:**
We run a workflow with the following configuration:
```yaml
      - name: Setup go version
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version: ${{ inputs.go-version }}
          check-latest: ${{ inputs.go-version-latest }}
          cache-dependency-path: ${{ inputs.working-directory }}
```

This results in several hundred MB of cached objects to be created with unique names and never cleaned up.

**Expected behavior:**
Only a few cached objects will be created and used, alternatively allow cached objects to be better configured since we have to pay for the storage.

**Actual behavior:**
Each time we setup-go in a build (which can be 3-4 different jobs) creates duplicate caches that appear to never be reused or cleaned up when in an enterprise context.
