### ISSUE TITLE
Use version from module and another version in matrix testing

### ISSUE THREAD

**Issue by Jacalz** [actions/setup-go#450]
**Description:**
Describe your proposal.

I want to be able to do something like this where the used Go versions are set automatically in matrix testing without having to manually maintain the workflows. This is very useful when having many repositories with CI/CD infrastructure set up. To minimize the versions of Go used for testing, I want to test with the latest stable and the minimum version that the project supports, i.e. I want to use `stable` and the version from my `go.mod` file.

My idea is to be able to specify something like `go-version-file` inside the `go-version` field:

```yaml
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ 'go.mod', 'stable' ]
    name: Go ${{ matrix.go }} sample
    steps:
      - uses: actions/checkout@v4
      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
      - run: go run hello.go
```

**Justification:**
Justification or a use case for your proposal.

This is very useful when having many repositories with CI/CD infrastructure set up. To minimize the versions of Go used for testing, I want to test with the latest stable and the minimum version that the project supports, i.e. I want to use `stable` and the version from my `go.mod` file.

**Are you willing to submit a PR?**

Sorry. I'll let you handle this

**Comment by aparnajyothi-y** [comment]
Hello @Jacalz,
Thank you for creating this issue, we will investigate it and come back to you as soon as we have some feedback.

**Comment by myaaaaaaaaa** [comment]
A possible (untested) implementation:

```diff
diff --git a/src/main.ts b/src/main.ts
index 690d277..2fdeb8a 100644
--- a/src/main.ts
+++ b/src/main.ts
@@ -133,24 +133,27 @@ export function parseGoVersion(versionString: string): string {
   // fmt.Printf("go version %s %s/%s\n", runtime.Version(), runtime.GOOS, runtime.GOARCH)
   // expecting go<version> for runtime.Version()
   return versionString.split(' ')[2].slice('go'.length);
 }
 
 function resolveVersionInput(): string {
   let version = core.getInput('go-version');
-  const versionFilePath = core.getInput('go-version-file');
+  let versionFilePath = core.getInput('go-version-file');
 
   if (version && versionFilePath) {
     core.warning(
       'Both go-version and go-version-file inputs are specified, only go-version will be used'
     );
   }
 
   if (version) {
-    return version;
+    if (!version.endsWith('go.mod')) {
+      return version;
+    }
+    versionFilePath = version;
   }
 
   if (versionFilePath) {
     if (!fs.existsSync(versionFilePath)) {
       throw new Error(
         `The specified go version file at: ${versionFilePath} does not exist`
       );
```

**Comment by ardnew** [comment]
You can achieve this using a secondary job in your workflow to construct the build matrix for your actual build job. I just worked through this myself:

```yaml
# Triggered on every push or pull request event to any branch.
name: 'test(any): all'
on: { push, pull_request }
jobs:

  # Run `go list` to resolve the module's declared Go version
  # and store the result in ${{ outputs.version }}.
  go-mod-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.list.outputs.version }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - id: list
        run: |
          go list -m -f 'version={{.GoVersion}}' >> "${GITHUB_OUTPUT}"

  # Run all tests in all packages, and record coverages,
  # on latest versions of Ubuntu, macOS, and Windows
  # using Go module version and other notable releases.
  build:
    needs: [ go-mod-version ]
    strategy:
      matrix:
        os: [ ubuntu, macos, windows ]
        go: [ '1.13', '1.19', "${{ needs.go-mod-version.outputs.version }}" ]
        include: [ version: latest ]
    runs-on: ${{ matrix.os }}-${{ matrix.version }}
    name: |
      Go ${{ matrix.go }} (${{ matrix.os }}-${{ matrix.version }})
    env:
      coverprofile: 'cover.out'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - name: Build
        run: |
          go build -v ./...
      - name: Test
        run: |
          go test -v -covermode=count -coverprofile="${coverprofile}" ./...
```

**Comment by ccoVeille** [comment]
For record, and as a workaround I'm using @arnested github action (great one BTW) that read the oldest go.mod that can be used to create a matrix with all versions between the go.mod one and stable ones, and even the future -rc if requested

https://github.com/arnested/go-version-action

**Comment by ccoVeille** [comment]
I opened https://github.com/actions/setup-go/pull/693

- https://github.com/actions/setup-go/pull/693

**Comment by v-gowridurgad** [comment]
Hi @Jacalz, thanks for raising this and to everyone who contributed to the discussion.


The described use case can be achieved today with setup-go by combining go-version and go-version-file, using an empty string ('') in the matrix to fall back to the version file. This lets a matrix run across the Go versions of your choice (for example, stable, oldstable) along with the version pinned in go.mod, in a single setup-go step and without duplicating the version in the workflow, as shared by @ccoVeille.

For example:
```
jobs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['stable', ''] # empty string to fall back on go-version-file
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup Go
        uses:  actions/setup-go@v7
        with:
          go-version: ${{ matrix.go-version }}
         go-version-file: 'go.mod'  # used only when go-version is not specified
```

Could you give this pattern a try in your workflow and let us know if it addresses your use case? Thanks!
