### ISSUE TITLE
Please upgrade `go-actions` to 1.21.8

### ISSUE THREAD

**Issue by silverwind** [actions/setup-go#462]
**Description:**
[go-versions](https://github.com/actions/go-versions) dependency is out of date, leading to all repos that use `setup-go` in combination with `govulncheck` to fail on the new vulnerabilities.

**Action version:** `5`
**Platform:** all
**Runner type:** all
**Tools version:** go 1.21

**Repro steps:**  
```
steps:
  - uses: actions/setup-go@v5
  with:
    go-version-file: "^1.21"
    check-latest: true
```

**Expected behavior:**
```
Setup go version spec 1.21
Attempting to resolve the latest version from the manifest...
matching 1.21...
Resolved as '1.21.8'
```

**Actual behavior:**
```
Setup go version spec 1.21
Attempting to resolve the latest version from the manifest...
matching 1.21...
Resolved as '1.21.7'
```
