### ISSUE TITLE
Can't cache dependencies from a composite action

### ISSUE THREAD

**Issue by dkirrane** [actions/setup-go#467]
**Description:**
I have a repo with a `go.mod` and `go.sum` and I caller another repo that contains a composite action that checks out the caller repo and calls `actions/setup-go@v5`

```yaml
name: Go Test

runs:
  using: "composite"

  steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version-file: test/go.mod
        cache-dependency-path: test/go.sum

    - name: go test
      run: |
        cd test/
        go test
      shell: bash
```

**Action version:**
actions/setup-go@v5

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**
go 1.21

**Repro steps:**  

Caller repo calling the above composite action:
```yaml
name: Caller

on:
  workflow_dispatch:

jobs:

  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Go Test
        uses: company/gotest-action/test@main

```

**Expected behavior:**
I was expecting dependencies to cache

**Actual behavior:**
`Cache is not found`
```
Run actions/setup-go@v5
Setup go version spec 1.21
Found in cache @ /opt/hostedtoolcache/go/1.21.8/x64
Added go to the path
Successfully set up Go version 1.21
/opt/hostedtoolcache/go/1.21.8/x64/bin/go env GOMODCACHE
/opt/hostedtoolcache/go/1.21.8/x64/bin/go env GOCACHE
/home/runner/go/pkg/mod
/home/runner/.cache/go-build
Cache is not found
go version go1.21.8 linux/amd64
```

**Comment by matthewhughes934** [comment]
>  I was expecting dependencies to cache

Just to clarify: you're seeing the cache not found on repeated runs on the same branch in the calling repo?

Do you see the cache being successfully saved on a previous run with a line like (in the `Post Go Test` section):

> Cache saved with the key: setup-go-Linux-ubuntu22-....

**Comment by aparnajyothi-y** [comment]
Hello @dkirrane, Thank you for creating this issue and we will look into it :)

**Comment by dkirrane** [comment]
@matthewhughes934 - yes to confirm re-runs always download dependencies again

![image](https://github.com/actions/setup-go/assets/1280116/85779fca-a0ac-4731-9443-85a259be67f4)

I can see there is 1 cache

![image](https://github.com/actions/setup-go/assets/1280116/46577d06-4975-40a3-a522-86cbc4ef06da)

**Comment by matthewhughes934** [comment]
> to confirm re-runs always download dependencies again

:+1: in that case is your issue related to the first run of the action? From what I understand cache access is limited _to workflows the repo they were created in_ (from: https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#restrictions-for-accessing-a-cache) so I wouldn't expect the first run to hit any cache

**Comment by dkirrane** [comment]
Ok, seems similar to this https://github.com/actions/toolkit/issues/1035
I'll try the workaround suggested

**Comment by priyagupta108** [comment]
Hello @dkirrane 👋,
I've attempted to reproduce the issue on my end, but was unable to do so. In my test environment, caching and reuse of dependencies worked as expected. It appears that the issue might be confined to your specific setup or workflow configuration.
Could you please provide a link to a minimal reproduction of the issue? It would be very helpful in addressing your issue. Thank you!

**Comment by priyagupta108** [comment]
Hello @dkirrane,
Just a gentle reminder about the issue. If you could provide a minimal reproduction of the problem, it would help us in investigating this further. Thank you in advance!

**Comment by priyagupta108** [comment]
Hello @dkirrane👋 , A gentle reminder regarding the problem. A minimal reproduction of the problem from your end would be a great help. We look forward to your response. Thank you!

**Comment by priyagupta108** [comment]
Hello @dkirrane👋,
Due to inactivity, I'm going to close this issue for now. Please feel free to reopen the issue if necessary, or create a new one. Thank you :)

**Comment by taraspos** [comment]
Hi @priyagupta108 I just faced the same problem and I can provide more information on how to reproduce it.

Long story short:
If composite action is used like `uses: {owner}/{repo}/.github/workflows/{filename}@{ref}`[^1] then it will be checked out automatically in to the `/home/runner/work/_actions/` folder. Absolute path can be retrieved from `github.action_path` [^2] context variable.  
[^1]: https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_iduses
[^2]: https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/accessing-contextual-information-about-workflow-runs#github-context

So when using `setup-go` inside composite action, you would want to do it in a following way:

```yaml
    - uses: actions/setup-go@v5
      with:
        go-version-file: ${{ github.action_path }}/go.mod
        cache-dependency-path: ${{ github.action_path }}/go.sum
```

However, if you do so then cache restore will fail with error `Some specified paths were not resolved, unable to cache dependencies.`.


This is because `setup-go` is trying to do `glob.hashFiles(dependencyFilePath)` on the `cache-dependency-path`.

- https://github.com/actions/setup-go/blob/3041bf56c941b39c61721a86cd11f3bb1338122a/src/cache-restore.ts#L22-L31


And it seems like `hashFiles` function skips files outside of `GITHUB_WORKSPACE`:
- https://github.com/actions/toolkit/blob/01f21badd5a7522507f84558503b56c4deec5326/packages/glob/src/internal-hash-files.ts#L23-L26
