### ISSUE TITLE
Dependencies file is not found. Supported file pattern: go.sum

### ISSUE THREAD

**Issue by fmunteanu** [actions/setup-go#476]
**Description:**
I'm getting this warning, on my [workflow](https://github.com/fmunteanu/hugo-test/blob/main/.github/workflows/hugo.yml):

```
Warning: Restore cache failed: Dependencies file is not found in /home/runner/work/hugo-test/hugo-test. Supported file pattern: go.sum
```

![image](https://github.com/actions/setup-go/assets/19806136/3237006e-ce33-4fef-a252-e1cc8768a3b1)

There is a previous issue https://github.com/actions/setup-go/issues/281, where the solution was to have the `checkout` executed prior `setup-go`, which is not the case for my [workflow](https://github.com/fmunteanu/hugo-test/blob/main/.github/workflows/hugo.yml).

**Action version:**
`setup-go@v5`

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**
`go1.22.2 linux/amd64`

**Repro steps:**  
See the related `Setup Go` step, into [workflow](https://github.com/fmunteanu/hugo-test/actions/runs/8914384911/job/24481865932) details.

**Expected behavior:**
No warnings should be generated.

**Actual behavior:**
Workflow output:
```
Run actions/setup-go@v5
  with:
    go-version: 1.22.x
    check-latest: false
    token: ***
    cache: true
Setup go version spec 1.22.x
Found in cache @ /opt/hostedtoolcache/go/1.22.2/x64
Added go to the path
Successfully set up Go version 1.22.x
/opt/hostedtoolcache/go/1.22.2/x64/bin/go env GOMODCACHE
/opt/hostedtoolcache/go/1.22.2/x64/bin/go env GOCACHE
/home/runner/.cache/go-build
/home/runner/go/pkg/mod
Warning: Restore cache failed: Dependencies file is not found in /home/runner/work/hugo-test/hugo-test. Supported file pattern: go.sum
go version go1.22.2 linux/amd64
```

**Comment by fmunteanu** [comment]
I'm not sure what effect has disabling the cache, but when I do this, the warning is gone. New step, with cache disabled:

```
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          cache: false
          go-version: 1.22.x
```

Workflow [build step](https://github.com/fmunteanu/hugo-test/actions/runs/8942793397/job/24566099934) has no more errors:

![image](https://github.com/actions/setup-go/assets/19806136/e0c71780-9553-49a2-9b9e-2645664879fc)

**Comment by HarithaVattikuti** [comment]
Hello @fmunteanu 
Thank you for creating this issue. We will investigate it and get back to you as soon as we have some feedback.

**Comment by peterbourgon** [comment]
See #478.

**Comment by fmunteanu** [comment]
Setting the step to:

```yaml
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          cache: true
          cache-dependency-path: |
            **/go.mod
            **/go.sum
```

Produces another error, see `Post Setup Go` step in [workflow](https://github.com/fmunteanu/hugo-test/actions/runs/9026526539/job/24803965885):

```
Post job cleanup.
/opt/hostedtoolcache/go/1.22.2/x64/bin/go env GOMODCACHE
/opt/hostedtoolcache/go/1.22.2/x64/bin/go env GOCACHE
/home/runner/go/pkg/mod
/home/runner/.cache/go-build
Warning: Cache folder path is retrieved but doesn't exist on disk: /home/runner/go/pkg/mod
Cache hit occurred on the primary key setup-go-Linux-ubuntu22-go-1.22.2-2e41450b046298d453631013dd695b7dd7b55d9f5c798193b859fd911bbdba7a, not saving cache.
```

**Comment by tamird** [comment]
This also happens in https://github.com/petermattis/goid because that library has no dependencies, and Go doesn't create a `go.sum` file unless there are at least some dependencies.

It would be good to avoid the warning in such cases.

**Comment by KathiravanKrish** [comment]
Hi @fmunteanu, The below workflow file have resolved the warning message issue. By adding steps to create the mod cache directory and cache the modules, we ensured that the cache folder path exists before it's accessed by the cache action. This eliminates the warning about the cache folder path not existing on the disk.
Going forward, this setup should provide a smoother run for your Go workflows. If you encounter any more issues or have other questions, don't hesitate to ask.

  ```
  - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.22.x
        cache: true

    - name: Create mod cache directory
      run: mkdir -p /home/runner/go/pkg/mod

    - name: Cache modules
      uses: actions/cache@v2
      with:
        path: /home/runner/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
```
