### ISSUE TITLE
[Bug] CGO_ENABLED on macos amd64 is not correct

### ISSUE THREAD

**Issue by timandy** [actions/setup-go#477]
**Description:**

**Action version:**
actions/setup-go@v5

**Platform:**
- [ ] Ubuntu
- [x] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**
go 1.18
go 1.19

**Repro steps:**  
```yml
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      # darwin
      - name: 'Test on [darwin] arch [amd64]'
        if: ${{ matrix.os == 'darwin' && contains(fromJson('["amd64"]'), matrix.arch) }}
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
        run: |
          echo ${CGO_ENABLED}   //print empty
          go env CGO_ENABLED //print 0 - should be 1
```

**Expected behavior:**
 go env CGO_ENABLED //should be 1

**Actual behavior:**
printed 0, On windows and linux print 1

mac 
https://github.com/timandy/routine/actions/runs/8965563348/job/24619393933#step:4:11

linux
https://github.com/timandy/routine/actions/runs/8965563348/job/24619398442#step:6:11
