### ISSUE TITLE
Cache `go install`-ed binaries

### ISSUE THREAD

**Issue by SirSova** [actions/setup-go#483]
**Description:**
Cache `go install`-ed binaries (optionally I suppose) along with go mod dependencies. Store `$GOBIN` folder with all installed during workflow execution binaries on post step (cache save).

**Justification:**
In my scenario, I use `tparse` tool to prettify tests results. I can imagine other cases such as code generator tools. Basically pre-run/post-run scripts. For now, I turned off the cache option of this action and wrote my own using `action/cache`, but it adds significant complexity to keep it around multiple workflows the same way.

**Are you willing to submit a PR?**
Sure, as soon as the feature is approved.

**Comment by HarithaVattikuti** [comment]
Hello @SirSova 
We appreciate your suggestion for a new feature! We'll make sure to address it when we have the opportunity

**Comment by silverwind** [comment]
I don't know what `GOBIN` is, but `GOMODCACHE` (`go env GOMODCACHE`) is generally cachable and caching it would speed up any `go run tool@version` or `go install tool@version` invokations, so it would be welcome to include them in the caching.

**Comment by SirSova** [comment]
`GOBIN` represents `$(go env GOPATH)/bin`. It's an env for the folder with all go-installed binaries.

So if I run `go install tool@version` -- it won't add a new dependency in my `go.mod` (meaning it won't be cached), but inside my GH workflows I do this:
```shell
go install github.com/mfridman/tparse@vX.Y.Z
go test -json  ./... | tparse -all
```
It will download and build `tparse` tool on each run which I want to avoid. 
And since these installations managed by Go, I believe that it's appropriate to do using `setup-go` action

**Comment by silverwind** [comment]
I have been experimenting using https://github.com/actions/cache and got some good results by caching `GOCACHE` and `GOMODCACHE` but I see it as a bit of risky activity because it relies on golang correctly invalidating its cach which I'm not fully trusting yet.

**Comment by StefMa** [comment]
Even through I would love to have this feature build in into this action, I honestly think it's not the responsibility of this action to cache such things.

This action is designed to install go, not more. What you're doing with go is not really part of this action. Is it? 🤔

**Comment by tak11173132** [comment]
> I don't know what `GOBIN` is, but `GOMODCACHE` (`go env GOMODCACHE` aka. `$GOPATH/pkg/mod`) is generally cachable and caching it would speed up any `go run tool@version` or `go install tool@version` invokations, so it would be welcome to include them in the caching.

**Comment by silverwind** [comment]
> Even through I would love to have this feature build in into this action, I honestly think it's not the responsibility of this action to cache such things.
> 
> This action is designed to install go, not more. What you're doing with go is not really part of this action. Is it? 🤔

I tend to agree that caching should not be in scope of `setup-*` actions, but apparently these features have been creeping into them and `setup-go` is as far as I'm aware the only action that enables caching by default.

**Comment by nferch** [comment]
I too would appreciate this feature. Even if it just cached the dependencies for something that was `go install`'d, that'd speed up my builds quite a bit.

I'm a bit confused/ignorant as to why this isn't happening already. I have multiple workflows that run at the same time on the same commit, is it that the first run that completes doesn't contain the cached modules in `GOMODCACHE`?

**Comment by zaibon** [comment]
> I have been experimenting using https://github.com/actions/cache and got some good performance results by caching GOCACHE (build cache) and GOMODCACHE (modules cache) but I see it as a bit of risky activity because it relies on golang correctly invalidating its cache and I'm not fully trusting it yet.

@silverwind can you share your solution in the mean time, while this issue is being decided/worked on ?

**Comment by silverwind** [comment]
Here is what I have been experimenting with and it seemed to work. The cache key surely is too aggressive and GOVERSION and go.mod hash can likely be removed.

```yaml
- uses: actions/setup-go@v5
  with:
    go-version-file: go.mod
    check-latest: true
- id: vars
  run: |
    echo "GOCACHE=$(go env GOCACHE)" >> "$GITHUB_OUTPUT"
    echo "GOMODCACHE=$(go env GOMODCACHE)" >> "$GITHUB_OUTPUT"
    echo "GOVERSION=$(go env GOVERSION)" >> "$GITHUB_OUTPUT"
- uses: actions/cache/restore@v4
  with:
    path: |
      ${{ steps.vars.outputs.GOCACHE }}
      ${{ steps.vars.outputs.GOMODCACHE }}
    key: golint-v1-${{ github.job }}-${{ runner.os }}-${{ runner.arch }}-${{ steps.vars.outputs.GOVERSION }}-${{ hashFiles('go.mod') }}
- run: make lint test
- uses: actions/cache/save@v4
  with:
    path: |
      ${{ steps.vars.outputs.GOCACHE }}
      ${{ steps.vars.outputs.GOMODCACHE }}
    key: golint-v1-${{ github.job }}-${{ runner.os }}-${{ runner.arch }}-${{ steps.vars.outputs.GOVERSION }}-${{ hashFiles('go.mod') }}
```

**Comment by nferch** [comment]
@silverwind thanks for sharing!

That seems to work for me, although the `actions/cache/restore` generates warnings when it tries to overwrite files that the `actions/setup-go` action restored from its cache.

I was able to achieve similar results by adding my `Makefile` to the `cache-dependency-path` value, which has two effects:

* It keys the cache using the Makefile, which includes versions of the tools that are installed, so the cache is repopulated when the versions change
* It forces a separate cache key from my main build workflow, which doesn't install or run the tools. This ensures that the cache used by this workflow contains the tools.

**Comment by peterbourgon** [comment]
Running

```
go install github.com/mfridman/tparse@v0.14.0
```

will create a binary named `tparse` in `$GOPATH/bin` (if $GOPATH is set) or in `$HOME/go/bin` (if $GOPATH is not set). That binary will be tparse at version v0.14.0, but that version is not represented in the binary filename, or in anything else that can be reasonably captured by a cache key. So you can't really cache `$GOPATH/bin` (or `$HOME/go/bin`), at least not effectively.

**Comment by zaibon** [comment]
> will create a binary named tparse in $GOPATH/bin (if $GOPATH is set) or in $HOME/go/bin (if $GOPATH is not set). That binary will be tparse at version v0.14.0, but that version is not represented in the binary filename, or in anything else that can be reasonably captured by a cache key. So you can't really cache $GOPATH/bin (or $HOME/go/bin), at least not effectively.

The trick there is to allow the user to define a cache key that is generated from the script that contain `go install github.com/mfridman/tparse@v0.14.0`. This is where the version exists, so it can be used as cache key.

**Comment by Zxilly** [comment]
`go install` downloads the code, compiles it, and then puts the binary in a directory. But there is no standard way of describing the version of the program being installed, and each time `go install` is executed it is a brand new installation, so how should the cache key be designed? Should the cache key be designed to keep track of each `go install` call? I can almost visualize a big pile of ugly workaround code already.

**Comment by SirSova** [comment]
The first run of `go install` does it, but it's 100% not a brand-new installation for the next calls. 
Just try it out. The 2nd+ calls are almost instantaneous. It must cache at least all dependencies. 
The workaround described above (GH workflow) worked for me perfectly.

**Comment by silverwind** [comment]
> But there is no standard way of describing the version of the program being installed

Since go 1.16, you can use `go install module@version` and `go run module@version` to specify the version.

**Comment by Zxilly** [comment]
yes, you can specify version, but after the install no way to get that.
The second install call faster because go compiler cache the middle object files, but the final binary still been created duplicate.

**Comment by peterbourgon** [comment]
@SirSova 

```yaml
      - name: Cache go modules
        uses: actions/cache@v4
        with:
          # /go/bin is for `go install`-ed tools
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
            ~/go/bin
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Run tests
        run: >
        go install github.com/mfridman/tparse@v0.14.0
        go test -json  ./... | tparse -all
```

`go install github.com/mfridman/tparse@v0.14.0` leverages cached dependencies in e.g. ~/.cache/go-build and ~/go/pkg/mod, but always writes a new tparse binary in ~/go/bin. So at least in this specific case, where you always `go install` tparse before using it, caching (and restoring) ~/go/bin doesn't really help you. If anything, it makes your workflow slower, because it makes the cache larger.

**Comment by oxisto** [comment]
Just to give some additional workaround ideas: It is possible to create a separate *folder*, e.g., tools with its own `go.mod` that looks like this (just for example)

```
module tools

go 1.23.4

require (
	github.com/99designs/gqlgen v0.17.61
	github.com/mfridman/tparse v0.16.0
	github.com/sqlc-dev/sqlc v1.27.0
)
```

Put also an additional tools.go file
```go
//go:build tools
// +build tools

package tools

import (
	_ "github.com/99designs/gqlgen"
	_ "github.com/mfridman/tparse"
	_ "github.com/sqlc-dev/sqlc/cmd/sqlc"
)
```

This has the advantage that the tool dependencies will not leak into your main go.mod. Then use the additional `cache-dependency-path: "**/*.sum"` in your setup-go action. This will also cache your build / tools dependencies.

I wonder whether some of this workflow will be made obsolete by the new tool directive in Go 1.24 (https://tip.golang.org/doc/go1.24#tools)

**Comment by kema-dev** [comment]
I'm using this kind of steps for an action, works like a charm. However, having a flag in `setup-go` to add caching for global packages would be nice (or better, integrating with `go tool`)


```yaml
runs:
  using: composite
  steps:
    - name: Set up Go
      id: setup-go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
        cache-dependency-path: go.sum
    - name: Get tool go.mod for cache key
      id: get-tool-go-mod-for-cache-key
      shell: bash
      run: |
        declare tool_go_mod_path="${{ runner.temp }}/tool-go.mod"
        echo "Fetching tool go.mod for cache key, storing at ${tool_go_mod_path}"
        curl --silent https://raw.githubusercontent.com/owner/repo/refs/heads/main/go.mod > "${tool_go_mod_path}"
        echo "Tool go.mod successfully fetched, stored at ${tool_go_mod_path}"
    - name: Cache Go install
      id: cache-go-install
      uses: actions/cache@v4
      with:
        path: |
          ~/go/bin
        key: go-install-${{ runner.os }}-${{ hashFiles('${{ runner.temp }}/tool-go.mod') }}
    - name: Install tool
      id: install-tool
      shell: bash
      run: |
        go install github.com/owner/repo@latest
```
