### ISSUE TITLE
Go version 1.22 gets parsed to 1.2.2

### ISSUE THREAD

**Issue by TLINDEN** [actions/setup-go#507]
**Description:**
When specifying a go version > 1.19 without patch level the action tries to download the wrong go version.

**Action version:**
I am using v5.

**Platform:**
- [X] Ubuntu
- [X] macOS
- [X] Windows

**Runner type:**
- [X] Hosted
- [ ] Self-hosted

**Tools version:**
1.20 and above.

**Repro steps:**  
When I specify a version like `1.20` or `1.22` it gets parsed to `1.2.2`:

Config:
```yaml
jobs:
  build:
    strategy:
      matrix:
        version: [1.22]
        os: [ubuntu-latest, windows-latest, macos-latest]                                                                         
    name: Build
    runs-on: ${{ matrix.os }}
    steps:
    - name: Set up Go 1.22 
      uses: actions/setup-go@v5
      with:
        go-version: '${{ matrix.version }}'
      id: go
```
Output of the "Set up" step:

```default
Run actions/setup-go@v5
Setup go version spec 1.2
Attempting to download 1.2...
matching 1.2...
Not found in manifest.  Falling back to download directly from Go
Install from dist
Acquiring go1.2.2 from https://storage.googleapis.com/golang/go1.2.2.linux-amd64.tar.gz
Extracting Go...
/usr/bin/tar xz --warning=no-unknown-keyword --overwrite -C /home/runner/work/_temp/d9f7282d-9b2a-4786-ade1-d97b9907ea26 -f /home/runner/work/_temp/4f50cd5d-f28d-4990-8333-3e436f3e1daf
Error: The operation was canceled.
```
As can be seen, even quoting doesn't prevent the behavior.

**Expected behavior:**
I'd expect that it uses the latest patch level of the specified go `1.22` (or whatever version above 1.20).

**Actual behavior:**
Version 1.2x gets parsed to 1.2.2.

---

A failing config can be seen [here](https://github.com/TLINDEN/tablizer/blob/f7d812b37286ddfa270682e700b0a849be54834c/.github/workflows/ci.yaml).

The workaround is to specify the whole version, e.g. `1.22.1`.

**Comment by priya-kinthali** [comment]
Hello @TLINDEN 👋,
Thank you for reporting this issue. We will investigate it and get back to you as soon as we have some feedback.

**Comment by matthewhughes-uw** [comment]
>  When I specify a version like 1.20 or 1.22 it gets parsed to 1.2.2:

There's a note about similar behaviour in the README

> Note: Due to the peculiarities of YAML parsing, it is recommended to wrap the version in single quotation marks:

I can see why `1.20` would be parsed to `1.2` (equivalent valued float) but I'm not so sure about `1.22`. Either way, I suspect just quoting the values should fix things

**Comment by priyagupta108** [comment]
Hi @TLINDEN, 
After reviewing the repository run you shared [here](https://github.com/TLINDEN/tablizer/actions/runs/11037155815), I found that Go versions 1.21 and 1.22 are functioning correctly and downloading the latest patches as expected. However, the behavior is specific to version 1.20. This is expected because it is related to YAML parsing.
To resolve this, please specify the version as follows:
```yaml
strategy:
      matrix:
        version: ['1.20']
```
For further details, you can refer to the [README](https://github.com/actions/setup-go#:~:text=Note%3A%20Due%20to,be%20very%20obvious).
