### ISSUE TITLE
Go 1.24rc1 not found

### ISSUE THREAD

**Issue by sonatard** [actions/setup-go#524]
**Description:**

I noticed that 1.24rc1 is not included in the manifest. Do you plan to support release candidates (RC) in the future?

https://github.com/actions/go-versions/blob/d75291c5c1691442f1a70c1d8a21cd1a044e1bde/versions-manifest.json

**Action version:**
v5

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**
Go 1.24rc1

**Repro steps:**  
```
    - uses: actions/setup-go@v5
      with:
        go-version: 1.24rc1
        cache: false
```

**Expected behavior:**
no error

**Actual behavior:**
```
Setup go version spec 1.24rc1
Attempting to download 1.24rc1...
matching 1.24rc1...
Not found in manifest.  Falling back to download directly from Go
Error: Unable to find Go version '1.24rc1' for platform linux and architecture x64.
```

**Comment by mahalakshmi-rekadi** [comment]
Hello @sonatard,
Thank you for creating this issue. We will investigate it and provide feedback as soon as we have some updates.

**Comment by priyagupta108** [comment]
Hi @sonatard 👋,
The action uses [SemVer notation for go-version input](https://github.com/actions/setup-go#v3). Therefore, you need to specify the version as `1.24.0-rc.1` instead of `1.24rc1`. Please update your workflow file to use the correct format:
```yaml
steps:
  - uses: actions/checkout@v4
  - uses: actions/setup-go@v5
    with:
      go-version: '1.24.0-rc.1'
  - run: go version
```
For more details on the supported version syntax, you can refer to the [setup-go documentation](https://github.com/actions/setup-go?tab=readme-ov-file#supported-version-syntax).
