### ISSUE TITLE
The RC version in the go.mod file cannot be retrieved

### ISSUE THREAD

**Issue by sonatard** [actions/setup-go#525]
**Description:**

RC is not included in the scope of the regular expression
https://github.com/actions/setup-go/blob/3041bf56c941b39c61721a86cd11f3bb1338122a/src/installer.ts#L467

**Action version:**
Specify the action version

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**
Go 1.24rc1

**Repro steps:**  

```
// go.mod
go 1.24rc1
```

```yaml
    - uses: actions/setup-go@v5
      with:
        go-version-file: ./${{ inputs.target }}/go.mod
        cache: false
```
**Expected behavior:**
```
Setup go version spec 1.24rc1
Attempting to download 1.24rc1...
matching 1.24rc1...
```

**Actual behavior:**
```
Setup go version spec 1.24
Attempting to download 1.24...
matching 1.24...
```
