### ISSUE TITLE
4.0.0 release text has smart quotes `‘1.19’`

### ISSUE THREAD

**Issue by jsoref** [actions/setup-go#526]
**Description:**
Smart quotes aren't valid, but the yaml for the 4.0.0 release uses them

**Action version:** 4.0.0

**Platform:**
- [x] Ubuntu
- [x] macOS
- [x] Windows

**Runner type:**
- [x] Hosted
- [x] Self-hosted

**Tools version:**
...

**Repro steps:**  
1. Visit https://github.com/actions/setup-go/releases/tag/v4.0.0

**Expected behavior:**
No smart quotes

**Actual behavior:**
```yaml
steps:
  - uses: actions/checkout@v3
  - uses: actions/setup-go@v4
    with:
      go-version: ‘1.19’
  - run: go run hello.go
```

Specifically this diff should be applied:
```diff
-      go-version: ‘1.19’
+      go-version: '1.19'
```

Note that this is a regression as v3.0.0 was fine: https://github.com/actions/setup-go/releases/tag/v3.0.0
