### ISSUE TITLE
"check-latest: true" doesn't bring Go 1.23.5

### ISSUE THREAD

**Issue by rosti-il** [actions/setup-go#540]
I have
```yml
  - uses: actions/setup-go@v5
    with:
      go-version: ${{inputs.go_version}}
      check-latest: true
```
With `inputs.go_version` defined as `1.23` instead of the previously defined `1.23.4` it still brings me the same version, although a newer `1.23.5` version of Go for the `actions/setup-go` is [released](https://github.com/actions/go-versions/releases/tag/1.23.5-12821973241) 2 days ago.

Logs from a running action:
```
Run actions/setup-go@v5
  with:
    go-version: 1.23
    check-latest: true
    token: ***
    cache: true
Setup go version spec 1.23
Attempting to resolve the latest version from the manifest...
matching 1.23...
Resolved as '1.23.4'
Attempting to download 1.23.4...
matching 1.23.4...
Acquiring 1.23.4 from https://github.com/actions/go-versions/releases/download/1.23.4-12152391001/go-1.23.4-linux-x64.tar.gz
Extracting Go...
```
