### ISSUE TITLE
Allow to use go-version and go-version-file at same time

### ISSUE THREAD

**Issue by ccoVeille** [actions/setup-go#547]
**Description:**

`go-version` already accepts `stable ` and `oldstable` aliases, they are great.

`go-version-file` was also a great addition, but these options cannot be used at same time.

As the documentation explains it clearly

> If both the go-version and the go-version-file inputs are provided then the go-version input is used.

**Justification:**

I would like to be able to use matrix with this

Take a look at this PR

https://github.com/monzo/typhon/pull/178

The version 1.19 had be hardcoded, while it was the one in the go.mod

I wish this could have been used

```yaml
name: Run Tests
on:
  - pull_request
jobs:
  test:
    strategy:
      matrix:
        go-version: ["go-version-file", "1.23.x"]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
				go-version-file: "go.mod"
```

I didn't check, but maybe it's working by using

```yaml
name: Run Tests
on:
  - pull_request
jobs:
  test:
    strategy:
      matrix:
        go-version: ["", "1.23.x"]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
				go-version-file: "go.mod"
```

But adding the alias "go-version-file" in go-version would make things clearer.

Also, maybe if accepted it could help with:
- #523

**Are you willing to submit a PR?**

Not yet, I'm opening the discussion for now.
