### ISSUE TITLE
Caching in Post Set up Go is very slow

### ISSUE THREAD

**Issue by Lenart12** [actions/setup-go#551]
**Description:**
Hi all. (I think) I am having an issue with caching speeds on Post set up go. It takes over 2 minuts to cache a 70mb cache, which to me sounds like way too long. Is this just the way it is, or should I do something to fix this. At this point it would be faster to disable the cache but I wonder anyway If im doing something wrong.

(full config is in the linked run below)
```yaml
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
```

**Action version:**
v4

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Repro steps:**  
https://github.com/Lenart12/TeslaBle2Mqtt/actions/runs/13229707370/job/36925124333
