### ISSUE TITLE
go-version-file enforces the minimum required Go version instead of opting for the maximum allowed one

### ISSUE THREAD

**Issue by azazeal** [actions/setup-go#561]
Given the following `go.mod` & `setup-go` configurations:

```
module github.com/actions/setup-go/example

go 1.23.3
```

```yaml
- name: Setup Go
  uses: actions/setup-go
  with:
    go-version-file: go.mod
```

the action would determine, today, that the version of Go it should setup is `1.23.3`, instead of `1.24.0`, which is the latest available Go version matching the `go` constraint the author opted for, as explained by the `go` directive documentation [here](https://go.dev/doc/modules/gomod-ref#go):

> go minimum-go-version
>
> minimum-go-version
>    The minimum version of Go required to compile packages in this module.

Perhaps there's good reason as to why the action determines the version as it does today, and if that's the case please let me know, but I think that, when `go-version-file` is used, the action should opt for the greatest available Go version matching the author's specification (perhaps only in cases where `check-latest` is set), instead of opting for the provided minimum required version.

**Comment by priya-kinthali** [comment]
Hello @azazeal👋,
Thank you for this feature request. We will investigate it and get back to you as soon as we have some feedback.

**Comment by azazeal** [comment]
> Hello [@azazeal](https://github.com/azazeal)👋, Thank you for this feature request. We will investigate it and get back to you as soon as we have some feedback.

Thank you for your response. I'd also like to point out the following:

Given two different `go.mod` files, carrying the constraints `go 1.23` & `go 1.23.4`, the action would determine, today and unless mistaken, the following Go versions, respectively: `1.23.6` & `1.23.4` but, perhaps, it should be `1.23.6` in both cases.

I can see how I'd like for my builds to run on the same minor version of a `go.mod` file (`1.23` in this example), just not quite sure why adding a patch constraint to the value the `go` directive carries, freezes the determined version to be _exactly that patch_, instead of it being determined as _at least that patch_,  especially in reference to the `go` directive's documentation.

This, of course, is just personal preference—just pointing it out.

**Comment by AlekSi** [comment]
See also #457

**Comment by polothy** [comment]
I'm not sure why, but seems like both `go` CLI and dependabot are sticking versions like `1.25.0` into `go.mod`. This seems like a security problem because now I'm getting 1.25.0 installed instead of latest version.  For example, this workflow fails because `govulncheck` finds CVEs in Go 1.25.0:

```yaml
  steps:
    - name: Setup Go
      uses: actions/setup-go@v6
      with:
        go-version-file: go.mod
        check-latest: true

    - name: Vulnerability Check
      shell: bash
      run: |
        go install golang.org/x/vuln/cmd/govulncheck@latest
        govulncheck ./...
```

When `go.mod` has 1.25.0 for the version of Go or for the toolchain. If you are not using `govulncheck`, then you might be building a distributing Go binaries with known CVEs.
