### ISSUE TITLE
Can't unlink already-existing object

### ISSUE THREAD

**Issue by pronebird** [actions/setup-go#601]
**Description:**

Workflow below:
```
- name: Install Go
   uses: actions/setup-go@v5
   with:
     go-version: 1.23.6
     cache-dependency-path: src/junkyard/go.sum
```

Caching is borked because of many issues like this:

```
../../../../go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20230927004350-cbd86285d259/go.mod: Can't unlink already-existing object: Permission denied
```

```
$ ls -la $HOME/go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20230927004350-cbd86285d259/go.mod 
-r--r--r--  1 nym  staff  3579 Jun 11 19:22 <REDACTED>/go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20230927004350-cbd86285d259/go.mod
```

Note that permission is read-only for the owner. 

[Based on this issue](https://github.com/golang/go/issues/35615), `go clean -modcache` should not have any problems with that.

**Action version:**
v5

**Platform:**
- [ ] Ubuntu
- [x] macOS
- [ ] Windows

**Runner type:**
- [ ] Hosted
- [x] Self-hosted

**Tools version:**
1.23.6

**Repro steps:**  
Run the same workflow with golang mod cache populated from previous run

**Expected behavior:**
Expected smooth sailing

**Actual behavior:**
Failure to delete golang mod cache
