### ISSUE TITLE
Some specified paths were not resolved, unable to cache dependencies.

### ISSUE THREAD

**Issue by pronebird** [actions/setup-go#602]
**Description:**
Caching does not seem to work on Ubuntu, the following warning is printed on each run:

> Restore cache failed: Some specified paths were not resolved, unable to cache dependencies. 

Workflow

```
- name: Install Go
   uses: actions/setup-go@v5
   with:
     go-version: 1.23.6
     cache-dependency-path: go/junkyard/go.sum
```

**Action version:**
v5

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [ ] Hosted
- [x] Self-hosted

**Tools version:**
go1.23.6

**Repro steps:**  
Add setup-go to workflow, specify path to go.sum via `cache-dependency-path` key.

**Expected behavior:**
No warning, working cache

**Actual behavior:**
Caching is not working
