### ISSUE TITLE
Golang 1.15 was released over one month ago

### ISSUE THREAD

**Issue by alessio** [actions/setup-go#74]
Hi!

Go 1.15 was [released on August 11th](https://blog.golang.org/go1.15), yet we can't yet [use it in our builds](https://github.com/cosmos/cosmos-sdk/pull/7014).

Please advise.

Thanks for considering.

(CC'ing @marbar3778)

**Comment by lrstanley** [comment]
This is becoming a very annoying issue to have to work around. setup-go is constantly behind versions by quite a bit. When the Go team releases a new Go version that has fixes for various CVE's, it's critical to be able to pull that version and be able to release new versions/run new builds based off that new version.

The past 8 versions or so, I've been constantly behind, expecting to be able to run another build, and have it pull in an older version (sometimes more than one patch version behind!).

`setup-go` should really not require manual adjustments to get new versions. Maybe it's worth not reinventing the wheel, and utilizing something like https://github.com/travis-ci/gimme?

**Comment by circa10a** [comment]
Maybe support `version : latest` ?

**Comment by hazcod** [comment]
FYI I use a Docker image in `.github/` which I update automatically with dependabot.
```
      -
        id: vars
        run: |
          echo ::set-output name=go_version::$(grep '^FROM go' .github/go/Dockerfile | cut -d ' ' -f 2 | cut -d ':' -f 2)
          echo "Using Go version ${{ steps.vars.outputs.go_version }}"
      -
        name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ steps.vars.outputs.go_version }}
```

**Comment by circa10a** [comment]
This will parse our the latest go version from the versions-manifest.json

``` 
-
        id: vars
        run: |
curl -s https://raw.githubusercontent.com/actions/go-versions/main/versions-manifest.json | grep -oE '"version": "[0-9]{1}.[0-9]{1,}(.[0-9]{1,})?"' | head -1 | cut -d':' -f2 | sed 's/ //g; s/"//g')
          echo "Using Go version ${{ steps.vars.outputs.go_version }}"
      -
        name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ steps.vars.outputs.go_version }}
```

**Comment by circa10a** [comment]
Alternatively:

```yaml
- id: vars
        run: |
          echo ::set-output name=go_version::$(curl -s https://raw.githubusercontent.com/actions/go-versions/main/versions-manifest.json | grep -oE '"version": "[0-9]{1}.[0-9]{1,}(.[0-9]{1,})?"' | head -1 | cut -d':' -f2 | sed 's/ //g; s/"//g')
          echo "Using Go version ${{ steps.vars.outputs.go_version }}"
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ steps.vars.outputs.go_version }}
```
