### ISSUE TITLE
Add Go 1.16beta1

### ISSUE THREAD

**Issue by 5idu** [actions/setup-go#96]

**Comment by mvdan** [comment]
I'm surprised this needs manual intervention, I thought just using https://golang.org/dl/?mode=json&include=all would work. It includes betas and RCs.

**Comment by pjvds** [comment]
@mvdan isn't this line breaking it?

https://github.com/actions/setup-go/blob/3b4dc6cbed1779f759b9c638cb83696acea809d1/src/installer.ts#L261

**Comment by pjvds** [comment]
It is support, you just need to specify `1.16.0-beta1`:

``` yaml
-
  name: Set up Go
  uses: actions/setup-go@v2
  with:
    stable: false
    go-version: 1.16.0-beta1
```
